begin;
create temporary table dispatch_test_results(test text primary key,passed boolean not null);
create temporary table dispatch_fixture(key text primary key,value text);
grant select,insert,update on dispatch_test_results,dispatch_fixture to authenticated,service_role;
insert into dispatch_fixture values('owner_uid',(select auth_user_id::text from public.team where role='owner' and status='active' limit 1));
insert into dispatch_fixture values('tech_uid',gen_random_uuid()::text),('other_uid',gen_random_uuid()::text),('lead','qa_dispatch_'||gen_random_uuid()::text),('partner','qa_partner_'||gen_random_uuid()::text),('tech','qa_tech_'||gen_random_uuid()::text),('other','qa_other_'||gen_random_uuid()::text);
insert into auth.users(id,email) select value::uuid,'qa-dispatch-'||value||'@example.invalid' from dispatch_fixture where key in ('tech_uid','other_uid');
insert into public.team(id,name,email,role,status,auth_user_id) values((select value from dispatch_fixture where key='tech'),'QA Dispatch Tech','qa-dispatch-tech@example.invalid','technician','active',(select value::uuid from dispatch_fixture where key='tech_uid')),((select value from dispatch_fixture where key='other'),'QA Other Tech','qa-dispatch-other@example.invalid','technician','active',(select value::uuid from dispatch_fixture where key='other_uid'));
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from dispatch_fixture where key='owner_uid'),'role','authenticated')::text,true);
set local role authenticated;
insert into public.lead_partners(id,name,phone,email) values((select value from dispatch_fixture where key='partner'),'QA partner','+12025550147','qa-source@example.invalid');
insert into public.leads(id,name,phone,address,service_requested,source,partner_id,app_data) values((select value from dispatch_fixture where key='lead'),'QA Customer','+12025550148','10 Test Street','Spring repair','QA partner',(select value from dispatch_fixture where key='partner'),'{"zip":"01757","state":"MA","city":"Milford","preferred_appointment":"2026-10-01","preferred_time":"8–10 AM"}');
do $$declare r jsonb;r2 jsonb;begin
 r:=public.approve_lead_for_dispatch((select value from dispatch_fixture where key='lead'));
 insert into dispatch_fixture values('job',r->>'job_id'),('customer',r->>'customer_id');
 r2:=public.approve_lead_for_dispatch((select value from dispatch_fixture where key='lead'));
 insert into dispatch_test_results values('approval is idempotent',r=r2);
 insert into dispatch_test_results select 'schedule preserved',scheduled_date='2026-10-01'::date and appointment_window='8–10 AM' from public.jobs where id=r->>'job_id';
 r:=public.create_lead_offer((select value from dispatch_fixture where key='lead'),(select value from dispatch_fixture where key='tech'));
 insert into dispatch_fixture values('offer',r->>'id');
 insert into dispatch_test_results values('five minute server deadline',(r->>'expires_at')::timestamptz-(r->>'created_at')::timestamptz=interval '5 minutes');
 begin perform public.create_lead_offer((select value from dispatch_fixture where key='lead'),(select value from dispatch_fixture where key='other'));raise exception 'TEST_FAILED duplicate offer accepted';exception when others then if sqlerrm not like '%An offer is still awaiting%' then raise;end if;end;
 insert into dispatch_test_results values('one pending offer per lead',true);
end$$;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from dispatch_fixture where key='other_uid'),'role','authenticated')::text,true);
do $$begin
 insert into dispatch_test_results values('other technician cannot see offer',not exists(select 1 from public.lead_offers where id=(select value::uuid from dispatch_fixture where key='offer')));
 begin perform public.respond_lead_offer((select value::uuid from dispatch_fixture where key='offer'),true);raise exception 'TEST_FAILED other technician accepted';exception when others then if sqlerrm not like '%Offer not available%' then raise;end if;end;
 insert into dispatch_test_results values('other technician cannot accept',true);
end$$;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from dispatch_fixture where key='tech_uid'),'role','authenticated')::text,true);
do $$declare r jsonb;begin
 insert into dispatch_test_results values('pending lead hidden',not exists(select 1 from public.leads where id=(select value from dispatch_fixture where key='lead'))),('pending job hidden',not exists(select 1 from public.jobs where id=(select value from dispatch_fixture where key='job'))),('pending customer hidden',not exists(select 1 from public.customers where id=(select value from dispatch_fixture where key='customer'))),('own ZIP offer visible',exists(select 1 from public.lead_offers where id=(select value::uuid from dispatch_fixture where key='offer') and zip='01757'));
 r:=public.respond_lead_offer((select value::uuid from dispatch_fixture where key='offer'),true);
 insert into dispatch_test_results values('accept links job',r->>'status'='accepted' and r->>'job_id'=(select value from dispatch_fixture where key='job'));
 insert into dispatch_test_results values('accepted full records visible',exists(select 1 from public.leads where id=(select value from dispatch_fixture where key='lead')) and exists(select 1 from public.jobs where id=(select value from dispatch_fixture where key='job')) and exists(select 1 from public.customers where id=(select value from dispatch_fixture where key='customer')));
 insert into dispatch_test_results values('repeat acceptance idempotent',public.respond_lead_offer((select value::uuid from dispatch_fixture where key='offer'),true)=r);
 begin update public.jobs set workflow_version=0 where id=(select value from dispatch_fixture where key='job');raise exception 'TEST_FAILED downgraded';exception when others then if sqlerrm not like '%Workflow version is server managed%' then raise;end if;end;
 insert into dispatch_test_results values('cannot bypass workflow version',true);
 begin update public.jobs set status='work_in_progress' where id=(select value from dispatch_fixture where key='job');raise exception 'TEST_FAILED work began without photos';exception when others then if sqlerrm not like '%Exterior arrival photo required%' then raise;end if;end;
 insert into dispatch_test_results values('start requires photos',true);
 begin perform public.register_job_evidence((select value from dispatch_fixture where key='job'),'exterior','job-evidence/missing.jpg');raise exception 'TEST_FAILED registered missing photo';exception when others then if sqlerrm not like '%Upload a job photo first%' then raise;end if;end;
 insert into dispatch_test_results values('missing storage object rejected',true);
end$$;
reset role;
-- Metadata-only upload fixtures, rolled back; no real files or outgoing messages.
insert into storage.objects(bucket_id,name,owner_id,metadata) select 'crm-assets','job-evidence/'||j.value||'/'||t.value||'/'||k||'.jpg',u.value,'{"mimetype":"image/jpeg"}'::jsonb from dispatch_fixture j,dispatch_fixture t,dispatch_fixture u cross join lateral (values('exterior'),('before'),('after')) kinds(k) where j.key='job' and t.key='tech' and u.key='tech_uid';
set local role authenticated;
do $$declare jid text;tid text;begin
 select value into jid from dispatch_fixture where key='job';select value into tid from dispatch_fixture where key='tech';
 perform public.register_job_evidence(jid,'exterior','job-evidence/'||jid||'/'||tid||'/exterior.jpg');
 update public.jobs set status='arrived' where id=jid;
 begin update public.jobs set status='work_in_progress' where id=jid;raise exception 'TEST_FAILED started without before photo';exception when others then if sqlerrm not like '%Before-work parts or work-area photo required%' then raise;end if;end;
 insert into dispatch_test_results values('exterior alone does not start work',true);
 perform public.register_job_evidence(jid,'before','job-evidence/'||jid||'/'||tid||'/before.jpg');
 update public.jobs set status='work_in_progress' where id=jid;
 insert into dispatch_test_results values('start succeeds after both photos',true);
 begin update public.jobs set status='work_finished' where id=jid;raise exception 'TEST_FAILED finished without after photo';exception when others then if sqlerrm not like '%Installed parts / finished work photo required%' then raise;end if;end;
 insert into dispatch_test_results values('finish requires after photo',true);
end$$;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from dispatch_fixture where key='owner_uid'),'role','authenticated')::text,true);
do $$begin
 begin insert into public.invoices(id,number,customer_id,job_id,items) values('qa_invoice_'||gen_random_uuid()::text,'QA-'||gen_random_uuid()::text,(select value from dispatch_fixture where key='customer'),(select value from dispatch_fixture where key='job'),'[{"qty":1,"rate":100,"taxable":false}]');raise exception 'TEST_FAILED invoice before after photo';exception when others then if sqlerrm not like '%Photograph installed parts / finished work before creating an invoice%' then raise;end if;end;
 insert into dispatch_test_results values('invoice requires completion evidence',true);
end$$;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from dispatch_fixture where key='tech_uid'),'role','authenticated')::text,true);
select public.register_job_evidence((select value from dispatch_fixture where key='job'),'after','job-evidence/'||(select value from dispatch_fixture where key='job')||'/'||(select value from dispatch_fixture where key='tech')||'/after.jpg');
update public.jobs set status='work_finished' where id=(select value from dispatch_fixture where key='job');
do $$declare inv text;again text;begin
 inv:=public.create_dispatch_invoice((select value from dispatch_fixture where key='job'),'[{"desc":"Labor","qty":1,"rate":100,"taxable":false}]','cash',15,'technician');
 insert into dispatch_fixture values('invoice',inv);
 again:=public.create_dispatch_invoice((select value from dispatch_fixture where key='job'),'[{"desc":"Labor","qty":1,"rate":100,"taxable":false}]','cash',15,'technician');
 insert into dispatch_test_results values('dispatch checkout is idempotent',again=inv);
 insert into dispatch_test_results select 'technician invoice links job and photos',job_id=(select value from dispatch_fixture where key='job') and jsonb_array_length(photos)=1 from public.invoices where id=inv;
 perform public.technician_record_quickpay_payment(inv,'cash',(select row_version from public.invoices where id=inv));
 insert into dispatch_test_results select 'technician records cash payment',jsonb_array_length(payments)=1 from public.invoices where id=inv;
end$$;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from dispatch_fixture where key='owner_uid'),'role','authenticated')::text,true);
update public.invoices set app_data=app_data||'{"receiptDeliveryStatus":"delivered"}'::jsonb where id=(select value from dispatch_fixture where key='invoice');
insert into dispatch_test_results values('UI receipt flag alone cannot close',not public.dispatch_job_ready((select value from dispatch_fixture where key='job')));
do $$begin
 begin insert into public.invoice_sms_receipts(invoice_id,sms_message_id) values((select value from dispatch_fixture where key='invoice'),'fake');raise exception 'TEST_FAILED client inserted receipt evidence';exception when insufficient_privilege then null;end;
 insert into dispatch_test_results values('client cannot forge SMS receipt correlation',true);
end$$;
reset role;
insert into dispatch_fixture values('sms','qa_sms_'||gen_random_uuid()::text);
insert into dispatch_fixture select 'payments',payments::text from public.invoices where id=(select value from dispatch_fixture where key='invoice');
set local role service_role;
insert into public.sms_messages(id,provider,direction,provider_message_id,remote_phone_number,normalized_remote_phone,message_text,provider_status) values((select value from dispatch_fixture where key='sms'),'inkbox','outbound','qa_sms_provider_'||gen_random_uuid()::text,'+12025550148','+12025550148','QA receipt metadata fixture','queued');
insert into public.invoice_sms_receipts(invoice_id,sms_message_id) values((select value from dispatch_fixture where key='invoice'),(select value from dispatch_fixture where key='sms'));
reset role;
insert into dispatch_test_results values('queued SMS receipt cannot close',not private.job_payment_receipt_ready((select value from dispatch_fixture where key='job')));
set local role service_role;
update public.sms_messages set provider_status='delivered' where id=(select value from dispatch_fixture where key='sms');
reset role;
insert into dispatch_test_results values('SMS status without delivery timestamp cannot close',not private.job_payment_receipt_ready((select value from dispatch_fixture where key='job')));
set local role service_role;
update public.sms_messages set delivered_at=now() where id=(select value from dispatch_fixture where key='sms');
reset role;
insert into dispatch_test_results values('provider delivered SMS receipt unlocks closure',private.job_payment_receipt_ready((select value from dispatch_fixture where key='job')));
set local role service_role;
update public.invoices set payments='[]'::jsonb where id=(select value from dispatch_fixture where key='invoice');
reset role;
insert into dispatch_test_results values('delivered receipt without payment cannot close',not private.job_payment_receipt_ready((select value from dispatch_fixture where key='job')));
set local role service_role;
update public.invoices set payments=(select value::jsonb from dispatch_fixture where key='payments') where id=(select value from dispatch_fixture where key='invoice');
update public.sms_messages set failed_at=now() where id=(select value from dispatch_fixture where key='sms');
reset role;
insert into dispatch_test_results values('failed SMS receipt cannot close',not private.job_payment_receipt_ready((select value from dispatch_fixture where key='job')));
reset role;
-- Trusted provider-event fixtures exercise correlation only; never contact the provider.
insert into dispatch_fixture values('receipt',gen_random_uuid()::text);
set local role service_role;
update public.invoices set app_data=app_data||jsonb_build_object('receiptEmailProviderMessageId',(select value from dispatch_fixture where key='receipt')) where id=(select value from dispatch_fixture where key='invoice');
insert into public.email_delivery_events(event_id,provider,provider_message_id,event_type,invoice_id,payload) values('qa_event_'||gen_random_uuid()::text,'resend',(select value from dispatch_fixture where key='receipt'),'email.delivered',(select value from dispatch_fixture where key='invoice'),'{}');
insert into public.audit_log(id,action,summary,entity_type,entity_id,related_id,source) values(gen_random_uuid()::text,'receipt_email_accepted','QA receipt fixture','invoices',(select value from dispatch_fixture where key='invoice'),(select value from dispatch_fixture where key='receipt'),'provider');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from dispatch_fixture where key='tech_uid'),'role','authenticated')::text,true);
set local role authenticated;
insert into dispatch_test_results values('paid receipt evidence unlocks closure',public.dispatch_job_ready((select value from dispatch_fixture where key='job')));
select public.complete_dispatch_job((select value from dispatch_fixture where key='job'),jsonb_build_object('name','QA Customer','dataUrl','data:image/png;base64,'||repeat('A',100)));
insert into dispatch_test_results select 'signed closure succeeds',status='completed' from public.jobs where id=(select value from dispatch_fixture where key='job');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from dispatch_fixture where key='owner_uid'),'role','authenticated')::text,true);
set local role authenticated;
insert into dispatch_fixture values('expired_lead','qa_expired_'||gen_random_uuid()::text);
insert into public.leads(id,name,phone,address,app_data) values((select value from dispatch_fixture where key='expired_lead'),'QA Expired Customer','+12025550149','11 Test Street','{"zip":"01757"}');
select public.approve_lead_for_dispatch((select value from dispatch_fixture where key='expired_lead'));
insert into dispatch_fixture select 'expired_offer',public.create_lead_offer((select value from dispatch_fixture where key='expired_lead'),(select value from dispatch_fixture where key='other'))->>'id';
reset role;
update public.lead_offers set expires_at=now()-interval '1 second' where id=(select value::uuid from dispatch_fixture where key='expired_offer');
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from dispatch_fixture where key='other_uid'),'role','authenticated')::text,true);
set local role authenticated;
insert into dispatch_test_results values('server rejects expired acceptance',public.respond_lead_offer((select value::uuid from dispatch_fixture where key='expired_offer'),true)->>'status'='expired');
insert into dispatch_test_results values('expired lead stays hidden',not exists(select 1 from public.leads where id=(select value from dispatch_fixture where key='expired_lead')));
reset role;
set local role service_role;
do $$declare a text;b text;begin
 a:=public.ingest_partner_message('sms','2025550147','qa-message','Customer referral: review these details.');b:=public.ingest_partner_message('sms','+12025550147','qa-message','Customer referral: review these details.');
 insert into dispatch_test_results values('partner inbound deduplicates',a is not null and a=b),('unknown partner ignored',public.ingest_partner_message('sms','+12025550100','qa-unknown','Unknown referral') is null),('referral never autoassigns',exists(select 1 from public.leads where id=a and assigned_technician_id is null and converted_job_id is null));
end$$;
reset role;
insert into dispatch_test_results values('clients cannot inherit privileged workflow role',not pg_has_role('authenticated','crm_workflow_executor','MEMBER'));
select jsonb_build_object('checks',count(*),'passed',bool_and(passed),'results',jsonb_agg(to_jsonb(r) order by test)) as report from dispatch_test_results r;
rollback;
