begin;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select auth_user_id from public.team where role='owner' and status='active' limit 1),'role','authenticated')::text,true);
create temp table wa_offer_checks(test text,passed boolean not null check(passed));
insert into wa_offer_checks values('service only',not has_function_privilege('authenticated','public.service_queue_wa_lead_offer(uuid,text)','execute') and not has_function_privilege('anon','public.service_queue_wa_lead_offer(uuid,text)','execute'));
do $$declare tid text:='qa_wa_'||gen_random_uuid(); lid text:='qa_wa_'||gen_random_uuid(); oid uuid:=gen_random_uuid(); worker uuid:=gen_random_uuid(); r jsonb;
begin
 insert into public.team(id,name,role,status,app_data) values(tid,'QA WhatsApp rollback','technician','active','{"whatsapp_number":"+12025550123","whatsapp_opt_in":true,"notify_prefs":{"newLead":true}}');
 insert into public.leads(id,name,phone,address,service_requested,source) values(lid,'QA rollback','+12025550123','PRIVATE TEST ADDRESS','Test','Test');
 insert into public.lead_offers(id,lead_id,technician_id,zip) values(oid,lid,tid,'01748');
 update public.wa_linked_status set state='ready',updated_at=clock_timestamp() where id='primary';
 r:=public.service_queue_wa_lead_offer(oid,'ZIP 01748 synthetic rollback only');
 insert into wa_offer_checks values('queued once',r->>'status'='queued');
 perform public.service_queue_wa_lead_offer(oid,'must not replace message');
 insert into wa_offer_checks select 'duplicate preserves first message',count(*)=1 and bool_and(body='ZIP 01748 synthetic rollback only') from public.wa_linked_sends where lead_offer_id=oid;
 update public.wa_linked_sends set created_at='2000-01-01' where lead_offer_id=oid;
 r:=public.service_claim_wa_linked_send(worker);
 insert into wa_offer_checks values('bridge receives queue command',r->>'request_id'=oid::text);
 update public.wa_linked_sends set state='submitted' where lead_offer_id=oid;
 insert into wa_offer_checks select 'submission status reaches offer',notification_status->'whatsapp'->>'status'='sent' from public.lead_offers where id=oid;
 delete from public.wa_linked_sends where lead_offer_id=oid;
 update public.team set app_data=jsonb_set(app_data,'{whatsapp_opt_in}','false') where id=tid;
 r:=public.service_queue_wa_lead_offer(oid,'blocked');
 insert into wa_offer_checks values('opt out honored',r->>'status'='blocked_no_opt_in');
 update public.team set app_data=jsonb_set(app_data,'{whatsapp_opt_in}','true') where id=tid;
 update public.wa_linked_status set state='disconnected';
 r:=public.service_queue_wa_lead_offer(oid,'offline');
 insert into wa_offer_checks values('offline explicitly reported',r->>'status'='not_connected');
 update public.wa_linked_status set state='ready',updated_at=clock_timestamp();
 perform public.service_queue_wa_lead_offer(oid,'expires before sending');
 update public.lead_offers set expires_at=clock_timestamp()-interval '1 second' where id=oid;
 perform public.service_claim_wa_linked_send(worker);
 insert into wa_offer_checks select 'expired queued offer cancelled',state='cancelled' from public.wa_linked_sends where lead_offer_id=oid;
end$$;
select * from wa_offer_checks;
rollback;
