begin;
create temporary table office_fixture(key text primary key,value text);
create temporary table office_results(test text primary key,passed boolean not null check(passed));
grant all on office_fixture,office_results to authenticated;
insert into office_fixture select k,'qa_office_'||gen_random_uuid()::text from unnest(array['office','tech','customer','job','estimate','invoice','product','supplier','po','photo','social','expense','task']) k;
insert into office_fixture values('office_uid',gen_random_uuid()::text),('tech_uid',gen_random_uuid()::text),('owner_uid',(select auth_user_id::text from public.team where role='owner' and status='active' limit 1));
insert into auth.users(id,email) select value::uuid,'qa-office-'||value||'@example.invalid' from office_fixture where key in ('office_uid','tech_uid');
insert into public.team(id,name,role,status,auth_user_id) values
 ((select value from office_fixture where key='office'),'QA Secretary','office','active',(select value::uuid from office_fixture where key='office_uid')),
 ((select value from office_fixture where key='tech'),'QA Office Technician','technician','active',(select value::uuid from office_fixture where key='tech_uid'));
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from office_fixture where key='office_uid'),'role','authenticated')::text,true);
set local role authenticated;
insert into office_results values('office resolves without owner privilege',public.is_office() and public.is_office_secretary() and not public.is_owner());
insert into public.customers(id,name) values((select value from office_fixture where key='customer'),'QA Office Customer');
insert into public.jobs(id,title,customer_id,technician_id,technician,scheduled_date) values((select value from office_fixture where key='job'),'QA Office Job',(select value from office_fixture where key='customer'),(select value from office_fixture where key='tech'),'QA Office Technician',null);
update public.jobs set app_data='{"parts_paid_by":"company"}',internal_notes='Secretary note' where id=(select value from office_fixture where key='job');
insert into office_results select 'office saves unscheduled job and operational details',scheduled_date is null and app_data->>'parts_paid_by'='company' from public.jobs where id=(select value from office_fixture where key='job');
insert into public.estimates(id,customer_id,converted_job_id) values((select value from office_fixture where key='estimate'),(select value from office_fixture where key='customer'),(select value from office_fixture where key='job'));
insert into office_results select 'office estimate links assigned job',estimate_id=(select value from office_fixture where key='estimate') from public.jobs where id=(select value from office_fixture where key='job');
insert into public.invoices(number,id,customer_id,job_id,items) values('QA-'||gen_random_uuid()::text,(select value from office_fixture where key='invoice'),(select value from office_fixture where key='customer'),(select value from office_fixture where key='job'),'[{"desc":"QA labor","qty":1,"rate":100}]');
update public.invoices set payments='[{"amount":100,"method":"Cash"}]',app_data='{"notes":"Office billing"}' where id=(select value from office_fixture where key='invoice');
insert into office_results select 'office records invoice and payment',jsonb_array_length(payments)=1 from public.invoices where id=(select value from office_fixture where key='invoice');
insert into public.products(id,name,qty) values((select value from office_fixture where key='product'),'QA office part',0);
update public.products set app_data='{"reorder_point":5}',rate=20 where id=(select value from office_fixture where key='product');
select public.adjust_product_stock('qa_adjust_'||gen_random_uuid()::text,(select value from office_fixture where key='product'),3,'manual','QA office receipt');
insert into office_results select 'office edits catalog and receives stock',qty=3 and rate=20 and app_data->>'reorder_point'='5' from public.products where id=(select value from office_fixture where key='product');
insert into public.suppliers(id,name) values((select value from office_fixture where key='supplier'),'QA Office Supplier');
insert into public.purchase_orders(id,supplier_id,status,line_items,app_data) values((select value from office_fixture where key='po'),(select value from office_fixture where key='supplier'),'draft','[]','{"number":"QA"}');
update public.purchase_orders set status='ordered',app_data='{"number":"QA","notes":"Office order"}' where id=(select value from office_fixture where key='po');
insert into office_results select 'office manages suppliers and orders',status='ordered' from public.purchase_orders where id=(select value from office_fixture where key='po');
insert into public.expenses(id,description,amount) values((select value from office_fixture where key='expense'),'QA receipt',10);
insert into public.tasks(id,title,assigned_to_id,status) values((select value from office_fixture where key='task'),'QA followup',(select value from office_fixture where key='office'),'open');
update public.tasks set app_data='{"notes":"Call customer"}' where id=(select value from office_fixture where key='task');
insert into office_results values('office saves expenses and delegated tasks',true);
insert into public.gallery_projects(id,title,photos) values((select value from office_fixture where key='photo'),'QA project','[]');
update public.gallery_projects set app_data='{"reference_product_id":"QA"}' where id=(select value from office_fixture where key='photo');
insert into public.social_posts(id,title,caption,platforms) values((select value from office_fixture where key='social'),'QA social','QA caption',array['instagram','facebook']);
update public.social_posts set status='ready' where id=(select value from office_fixture where key='social');
insert into office_results select 'office saves gallery and social drafts',status='ready' from public.social_posts where id=(select value from office_fixture where key='social');
do $$begin
 begin update public.social_posts set status='posted_manual' where id=(select value from office_fixture where key='social');raise exception 'TEST_FAILED unconfirmed publish';exception when check_violation then null;end;
 insert into office_results values('manual published status requires a post link',true);
 update public.team set phone='+12025550149',commission_percent=35 where id=(select value from office_fixture where key='tech');
 insert into office_results select 'office manages technician contact and commission',commission_percent=35 from public.team where id=(select value from office_fixture where key='tech');
 begin update public.team set role='owner' where id=(select value from office_fixture where key='tech');raise exception 'TEST_FAILED role escalation';exception when others then if sqlerrm not like '%contact details%' then raise;end if;end;
 insert into office_results values('office cannot promote technicians',true);
 begin update public.team set auth_user_id=null where id=(select value from office_fixture where key='tech');raise exception 'TEST_FAILED auth unlink';exception when others then if sqlerrm not like '%contact details%' then raise;end if;end;
 insert into office_results values('office cannot change account credentials',true);
 begin perform public.remove_team_member((select value from office_fixture where key='tech'));raise exception 'TEST_FAILED remove account';exception when others then if sqlerrm not like '%Only the owner%' then raise;end if;end;
 insert into office_results values('office cannot remove users',true);
 update public.team set role='owner' where id=(select value from office_fixture where key='office');
 insert into office_results values('office cannot elevate itself',public.current_app_role()='office');
 insert into office_results values('office receives only safe company settings',public.get_office_settings()?'cc_surcharge_percent' and not(public.get_office_settings()?'app_data') and not(public.get_office_settings()?'ai_receptionist'));
 insert into office_results values('raw owner settings remain inaccessible',not exists(select 1 from public.settings));
end$$;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select value from office_fixture where key='tech_uid'),'role','authenticated')::text,true);
insert into office_results values('technician cannot see social drafts',not exists(select 1 from public.social_posts));
do $$begin
 begin perform public.get_office_settings();raise exception 'TEST_FAILED settings leaked';exception when others then if sqlerrm not like '%Office access required%' then raise;end if;end;
 insert into office_results values('technician cannot call office settings API',true);
end$$;
reset role;
select jsonb_build_object('passed',count(*),'tests',jsonb_agg(test)) from office_results;
rollback;
