begin;
create temp table estimate_sign_results(test text,passed boolean not null check(passed));
create temp table estimate_sign_fixture(token text);
grant all on estimate_sign_results,estimate_sign_fixture to anon;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select auth_user_id from public.team where role='owner' and status='active' limit 1),'role','authenticated')::text,true);
insert into public.jobs(id,title,status,technician_id) values('qa_estimate_signature','QA estimate signature','scheduled',(select id from public.team where role='technician' and status='active' limit 1));
insert into public.estimates(id,number,converted_job_id,items,status) values('qa_estimate_signature','QA-ESTIMATE-SIGNATURE','qa_estimate_signature','[{"qty":1,"rate":50}]','draft');
insert into estimate_sign_fixture select public.issue_public_estimate_signing_token('qa_estimate_signature')->>'token';
select set_config('request.jwt.claims','{"role":"anon"}',true);
set local role anon;
do $$declare image text;t text;begin
 select token into t from estimate_sign_fixture;
 foreach image in array array[null,'','data:image/png;base64,','data:image/svg+xml;base64,AAAA','data:image/png;base64,not-valid!'] loop
  begin perform public.sign_public_estimate('qa_estimate_signature',t,'Synthetic',image,'v1');raise exception 'TEST_FAILED missing image approved';
  exception when others then if sqlerrm <> 'Signature must be a supported image data URL' then raise;end if;end;
  insert into estimate_sign_results values ('invalid image rejected: '||coalesce(image,'NULL'),true);
 end loop;
 begin perform public.sign_public_estimate('qa_estimate_signature',null,'Synthetic','data:image/png;base64,AAAA','v1');raise exception 'TEST_FAILED null token';
 exception when others then if sqlerrm <> 'Invalid estimate access token' then raise;end if;end;
 insert into estimate_sign_results values('null token rejected',true);
 begin perform public.sign_public_estimate('qa_estimate_signature',t,' ','data:image/png;base64,AAAA','v1');raise exception 'TEST_FAILED blank name';
 exception when others then if sqlerrm <> 'Signer name is required' then raise;end if;end;
 insert into estimate_sign_results values('blank signer rejected',true);
 begin perform public.sign_public_estimate('qa_estimate_signature',t,'Synthetic','data:image/png;base64,'||repeat('A',750001),'v1');raise exception 'TEST_FAILED oversized';
 exception when others then if sqlerrm <> 'Signature image is too large' then raise;end if;end;
 insert into estimate_sign_results values('oversized image rejected',true);
 begin perform public.sign_public_estimate('qa_estimate_signature',repeat('0',64),'Synthetic','data:image/png;base64,AAAA','v1');raise exception 'TEST_FAILED wrong token';
 exception when others then if sqlerrm <> 'Estimate signing link expired or invalid' then raise;end if;end;
 insert into estimate_sign_results values('wrong token rejected',true);
end$$;
reset role;
insert into estimate_sign_results select 'failed requests preserve draft and unused token',status='draft' and signature is null and not exists(select 1 from public.public_estimate_signing_tokens where estimate_id=e.id and used_at is not null) from public.estimates e where id='qa_estimate_signature';
set local role anon;
insert into estimate_sign_results select 'valid anonymous signing approves',public.sign_public_estimate('qa_estimate_signature',(select token from estimate_sign_fixture),'Synthetic','data:image/png;base64,AAAA','v1')->>'status'='approved';
insert into estimate_sign_results select 'repeat signing is idempotent',(public.sign_public_estimate('qa_estimate_signature',(select token from estimate_sign_fixture),'Another name','data:image/png;base64,BBBB','v1')->>'already_signed')::boolean;
reset role;
insert into estimate_sign_results select 'first signature preserved',status='approved' and signature->>'name'='Synthetic' and signature->>'dataUrl'='data:image/png;base64,AAAA' from public.estimates where id='qa_estimate_signature';
insert into estimate_sign_results select 'one signing audit',count(*)=1 from public.audit_log where entity_id='qa_estimate_signature' and action='estimate_signed_remote';
select jsonb_build_object('passed',count(*),'tests',jsonb_agg(test)) from estimate_sign_results;
rollback;
