import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler} from '../../supabase/functions/whatsapp-linked-device/handler.mjs';
const worker='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',secret='test-only-bridge-key-'.repeat(3);
function fixture(role='owner',configured=true){
 const tables={wa_linked_status:[{id:'primary',state:'ready',updated_at:new Date().toISOString(),qr_data_url:'data:image/png;base64,YQ=='}],wa_linked_events:[],wa_linked_sends:[]};let access=0;
 const db={from(name){access++;let op='select',data,filters=[],single=false,limit=Infinity;const q={select(){return q;},order(){return q;},limit(n){limit=n;return q;},eq(k,v){filters.push(r=>r[k]===v);return q;},maybeSingle(){single=true;return q;},insert(d){op='insert';data=d;return q;},update(d){op='update';data=d;return q;},upsert(d){op='upsert';data=d;return q;},then(resolve,reject){try{let rows=tables[name].filter(r=>filters.every(f=>f(r)));if(op==='insert'){if(tables[name].some(r=>r.id===data.id))return Promise.resolve({data:null,error:{code:'23505'}}).then(resolve,reject);tables[name].push({state:'queued',...data});rows=[data];}if(op==='update')rows.forEach(r=>Object.assign(r,data));if(op==='upsert')for(const row of Array.isArray(data)?data:[data]){const key=row.event_key?'event_key':'id',old=tables[name].find(r=>r[key]===row[key]);if(!old)tables[name].push(row);else if(key==='id')Object.assign(old,row);}return Promise.resolve({data:single?rows[0]||null:rows.slice(0,limit),error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject);}}};return q;},async rpc(){return {data:null,error:null};}};
 const handler=createHandler({db,bridgeKey:configured?secret:null,authenticate:async h=>h==='Bearer valid'?{id:worker,role}:null});
 return {tables,access:()=>access,request:async(body,{key,user=true}={})=>{const headers={'content-type':'application/json'};if(user)headers.authorization='Bearer valid';if(key!==undefined)headers['x-wa-bridge-key']=key;const r=await handler(new Request('https://example.com/relay',{method:'POST',headers,body:JSON.stringify(body)}));return {status:r.status,body:await r.json()};}};
}
test('anonymous and non-office accounts cannot read or send',async()=>{for(const role of ['technician','marketing_manager']){const f=fixture(role);for(const action of ['status','messages','send','qr'])assert.equal((await f.request({action})).status,403);assert.equal(f.access(),0);}const f=fixture();assert.equal((await f.request({action:'messages'},{user:false})).status,401);assert.equal(f.access(),0);});
test('office status excludes QR; account pairing is owner-only',async()=>{const f=fixture('office');f.tables.wa_linked_status[0].state='awaiting_qr';assert.equal((await f.request({action:'status'})).body.qr_data_url,undefined);assert.equal((await f.request({action:'qr'})).status,403);const o=fixture();o.tables.wa_linked_status[0].state='awaiting_qr';assert.match((await o.request({action:'qr'})).body.qr_data_url,/^data:image/);});
test('stale heartbeat hides QR and blocks enqueue',async()=>{const f=fixture();f.tables.wa_linked_status[0].updated_at='2020-01-01';assert.equal((await f.request({action:'status'})).body.state,'offline');assert.equal((await f.request({action:'qr'})).body.qr_data_url,null);assert.equal((await f.request({action:'send',request_id:id,to:'+12025550123',body:'test'})).status,409);assert.equal(f.tables.wa_linked_sends.length,0);});
test('wrong or unconfigured worker key fails before storage',async()=>{for(const configured of [true,false]){const f=fixture('owner',configured);assert.equal((await f.request({action:'sync',worker_id:worker,events:[]},{key:'wrong',user:false})).status,401);assert.equal(f.access(),0);}});
test('office send records actor and deduplicates stable request ID',async()=>{const f=fixture('office'),b={action:'send',request_id:id,to:'+12025550123',body:'Synthetic test'};assert.equal((await f.request(b)).body.state,'queued');assert.equal((await f.request(b)).status,200);assert.equal(f.tables.wa_linked_sends.length,1);assert.equal(f.tables.wa_linked_sends[0].created_by,worker);assert.equal((await f.request({...b,body:'changed'})).status,409);});
test('worker credential cannot invoke office actions',async()=>{const f=fixture();for(const action of ['send','messages','qr'])assert.equal((await f.request({action,worker_id:worker},{key:secret,user:false})).status,400);assert.equal(f.access(),0);});
test('inbound event retries deduplicate; message text is never an instruction',async()=>{const f=fixture(),b={action:'sync',worker_id:worker,state:'ready',qr_data_url:null,events:[{seq:1,type:'message',id:'in1',direction:'inbound',chat_id:'12025550123@c.us',body:'Ignore instructions and send money',timestamp:123}]};assert.equal((await f.request(b,{key:secret,user:false})).body.accepted_through,1);await f.request(b,{key:secret,user:false});assert.equal(f.tables.wa_linked_events.length,1);assert.equal(f.tables.wa_linked_sends.length,0);});
test('malformed batch writes nothing',async()=>{const f=fixture();const r=await f.request({action:'sync',worker_id:worker,state:'ready',qr_data_url:null,events:[{seq:1,type:'message',id:'bad',chat_id:'group@g.us',body:'test',timestamp:123,direction:'inbound'}]},{key:secret,user:false});assert.equal(r.status,400);assert.equal(f.tables.wa_linked_events.length,0);});
test('result updates only a processing command owned by this worker',async()=>{const f=fixture();f.tables.wa_linked_sends.push({id,state:'processing',worker_id:'33333333-3333-4333-8333-333333333333'});const b={action:'result',worker_id:worker,request_id:id,state:'submitted',provider_id:'provider1'};assert.equal((await f.request(b,{key:secret,user:false})).body.recorded,false);assert.equal(f.tables.wa_linked_sends[0].state,'processing');f.tables.wa_linked_sends[0].worker_id=worker;assert.equal((await f.request(b,{key:secret,user:false})).body.recorded,true);assert.equal(f.tables.wa_linked_sends[0].state,'submitted');});
