import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {Bridge} from './bridge.mjs';
import {Relay,relayTransport} from './relay.mjs';
const command={request_id:'request_000000001',to:'+12025550123',body:'Synthetic test only'};
function fixture(t){const client=new EventEmitter();let sends=0;client.getNumberId=async()=>({_serialized:'12025550123@c.us'});client.sendMessage=async()=>{sends++;return {id:{_serialized:'out1'}};};const bridge=new Bridge(client,':memory:');t.after(()=>bridge.close());client.emit('ready');return {bridge,client,sends:()=>sends};}
test('lost result acknowledgement replays command without duplicate send',async t=>{const f=fixture(t);let attempts=0;const relay=new Relay(f.bridge,async b=>{if(b.action==='sync')return {accepted_through:0,command};if(++attempts===1)throw Error('lost');return {ok:true};},()=>null);await assert.rejects(relay.tick());await relay.tick();assert.equal(f.sends(),1);assert.equal(attempts,2);});
test('cursor advances only after complete acknowledgement',async t=>{const f=fixture(t);f.bridge.record('one',{id:'one',type:'ack',ack:2});const batches=[];let fail=true;const relay=new Relay(f.bridge,async b=>{batches.push(b.events.map(e=>e.seq));if(fail)throw Error('network');return {accepted_through:b.events.at(-1)?.seq||0};},()=>null);await assert.rejects(relay.tick());fail=false;await relay.tick();await relay.tick();assert.deepEqual(batches,[[1],[1],[]]);});
test('identity and cursor survive relay restart',async t=>{const f=fixture(t);f.bridge.record('one',{id:'one',type:'ack',ack:2});const a=new Relay(f.bridge,async()=>({accepted_through:1}),()=>null);await a.tick();let seen;const b=new Relay(f.bridge,async body=>{seen=body;return {};},()=>null);await b.tick();assert.equal(a.workerId,b.workerId);assert.deepEqual(seen.events,[]);});
test('invalid acknowledgement does not discard local events',async t=>{const f=fixture(t);f.bridge.record('one',{id:'one',type:'ack',ack:2});const relay=new Relay(f.bridge,async()=>({accepted_through:999}),()=>null);await assert.rejects(relay.tick());assert.equal(f.bridge.db.prepare("SELECT value FROM relay_state WHERE key='cursor'").get(),undefined);});
test('one in-flight poll; HTTPS transport refuses redirects and credential URLs',async t=>{const f=fixture(t);let release,calls=0;const relay=new Relay(f.bridge,async()=>{calls++;await new Promise(r=>release=r);return {};},()=>null);const pending=relay.tick();await relay.tick();release();await pending;assert.equal(calls,1);for(const url of ['http://example.com','https://u:p@example.com','https://example.com/?key=x'])assert.throws(()=>relayTransport(url,'x'.repeat(32)));let options;await relayTransport('https://example.com/relay','x'.repeat(32),async(_,o)=>{options=o;return Response.json({ok:true});})({action:'sync'});assert.equal(options.redirect,'error');});
