import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SQUARE_VERSION = "2026-09-16";
const DEFAULT_NOTIFICATION_URL = "https://fylbalenuqpovwncwbah.supabase.co/functions/v1/square-webhook";
const SQUARE_SUBSCRIPTION_TEST_PAYMENT_ID = "hYy9pRFVxpDsO1FB05SunFWUe9JZY";
function json(data: unknown, status = 200) { return Response.json(data, { status, headers: { "Content-Type": "application/json" } }); }
async function hmacBase64(secret: string, message: string) { const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]); const signed=new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(message))); let binary=""; for(const b of signed) binary+=String.fromCharCode(b); return btoa(binary); }
function safeEqual(a:string,b:string){const aa=new TextEncoder().encode(a),bb=new TextEncoder().encode(b);if(aa.length!==bb.length)return false;let diff=0;for(let i=0;i<aa.length;i++)diff|=aa[i]^bb[i];return diff===0;}
function asNumber(v:unknown){const n=Number(v);return Number.isFinite(n)?n:0;}
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
Deno.serve(async(req:Request)=>{
 if(req.method!=="POST") return json({ok:false,error:"Method not allowed"},405);
 const supabaseUrl=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,squareToken=Deno.env.get("SQUARE_ACCESS_TOKEN"); if(!squareToken)return json({ok:false,error:"Square is not configured"},503);
 const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false}}); const rawBody=await req.text();
 const {data:config,error:configErr}=await admin.from("square_integration_config").select("webhook_signature_key,notification_url").eq("id","main").maybeSingle(); if(configErr)return json({ok:false,error:"Webhook configuration unavailable"},503);
 const signatureKey=String(config?.webhook_signature_key||""),notificationUrl=String(config?.notification_url||DEFAULT_NOTIFICATION_URL); if(!signatureKey)return json({ok:false,error:"Webhook signature key is not configured"},503);
 const supplied=req.headers.get("x-square-hmacsha256-signature")||"",expected=await hmacBase64(signatureKey,notificationUrl+rawBody); if(!supplied||!safeEqual(supplied,expected))return json({ok:false,error:"Invalid webhook signature"},403);
 let event:any; try{event=JSON.parse(rawBody)}catch{return json({ok:false,error:"Invalid JSON"},400)}
 const eventId=String(event?.event_id||"").trim(),eventType=String(event?.type||"").trim(),merchantId=String(event?.merchant_id||"").trim()||null; if(!eventId||eventId.length>160)return json({ok:false,error:"Missing event id"},400);
 const {data:prior}=await admin.from("square_webhook_events").select("status").eq("event_id",eventId).maybeSingle(); if(prior?.status==="processed"||prior?.status==="ignored")return json({ok:true,duplicate:true});
 if(!new Set(["payment.created","payment.updated"]).has(eventType)){await admin.from("square_webhook_events").upsert({event_id:eventId,event_type:eventType,merchant_id:merchantId,status:"ignored",processed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"event_id"});return json({ok:true,ignored:true});}
 const payloadPayment=event?.data?.object?.payment||{},paymentId=String(payloadPayment?.id||event?.data?.id||"").trim(),payloadStatus=String(payloadPayment?.status||"").toUpperCase();
 if(!paymentId){await admin.from("square_webhook_events").upsert({event_id:eventId,event_type:eventType,merchant_id:merchantId,status:"failed",error_text:"payment id missing",updated_at:new Date().toISOString()},{onConflict:"event_id"});return json({ok:false,error:"Payment id missing"},400);}
 if(paymentId===SQUARE_SUBSCRIPTION_TEST_PAYMENT_ID){await admin.from("square_webhook_events").upsert({event_id:eventId,event_type:eventType,merchant_id:merchantId,order_id:String(payloadPayment?.order_id||"")||null,payment_id:paymentId,status:"ignored",error_text:"Square webhook subscription test event",processed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"event_id"});return json({ok:true,test:true,ignored:true});}
 if(payloadStatus && payloadStatus!=="COMPLETED"){await admin.from("square_webhook_events").upsert({event_id:eventId,event_type:eventType,merchant_id:merchantId,order_id:String(payloadPayment?.order_id||"")||null,payment_id:paymentId,status:"ignored",processed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"event_id"});return json({ok:true,ignored:true,payment_status:payloadStatus});}
 const headers={"Authorization":`Bearer ${squareToken}`,"Content-Type":"application/json","Square-Version":SQUARE_VERSION};
 let paymentRes:Response|null=null,paymentJson:any={};
 for(const delay of [0,250,750,1500]){if(delay)await sleep(delay);paymentRes=await fetch(`https://connect.squareup.com/v2/payments/${encodeURIComponent(paymentId)}`,{headers});paymentJson=await paymentRes.json().catch(()=>({}));if(paymentRes.ok)break;const code=String(paymentJson?.errors?.[0]?.code||"");if(!["NOT_FOUND","INTERNAL_SERVER_ERROR","SERVICE_UNAVAILABLE"].includes(code))break;}
 if(!paymentRes?.ok){const message=paymentJson?.errors?.[0]?.detail||"Could not verify Square payment";await admin.from("square_webhook_events").upsert({event_id:eventId,event_type:eventType,merchant_id:merchantId,payment_id:paymentId,status:"failed",error_text:String(message).slice(0,500),updated_at:new Date().toISOString()},{onConflict:"event_id"});return json({ok:false,error:"Square payment verification failed"},502);}
 const payment=paymentJson?.payment||{},orderId=String(payment?.order_id||payloadPayment?.order_id||"").trim(),status=String(payment?.status||"").toUpperCase(); if(status!=="COMPLETED"||!orderId){await admin.from("square_webhook_events").upsert({event_id:eventId,event_type:eventType,merchant_id:merchantId,order_id:orderId||null,payment_id:paymentId,status:"ignored",processed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"event_id"});return json({ok:true,ignored:true,payment_status:status||"UNKNOWN"});}
 const {data:invoices,error:invErr}=await admin.from("invoices").select("id,number,app_data,payments").eq("payment_provider","square").is("deleted_at",null).eq("app_data->>squareOrderId",orderId).limit(2); if(invErr)throw invErr;
 if(!invoices?.length){await admin.from("square_webhook_events").upsert({event_id:eventId,event_type:eventType,merchant_id:merchantId,order_id:orderId,payment_id:paymentId,status:"ignored",error_text:"No CRM invoice matched Square order",processed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"event_id"});return json({ok:true,ignored:true,reason:"invoice_not_matched"});}
 if(invoices.length!==1)return json({ok:false,error:"Square order matched multiple invoices"},409); const inv:any=invoices[0],app=(inv.app_data&&typeof inv.app_data==="object")?inv.app_data:{},base=asNumber(app.squareCardBase),fee=asNumber(app.squareCardFee),charged=asNumber(app.squareCardTotal),actualCents=asNumber(payment?.amount_money?.amount),expectedCents=Math.round(charged*100);
 if(base<=0||charged<=0||actualCents!==expectedCents){await admin.from("square_webhook_events").upsert({event_id:eventId,event_type:eventType,merchant_id:merchantId,order_id:orderId,payment_id:paymentId,invoice_id:inv.id,status:"failed",error_text:"Square amount did not match CRM invoice",updated_at:new Date().toISOString()},{onConflict:"event_id"});await admin.from("audit_log").insert({id:`audit_sq_review_${Date.now()}_${crypto.randomUUID().slice(0,8)}`,action:"square_payment_review_required",summary:`Square payment amount did not match invoice ${inv.number||inv.id}`,entity_type:"invoices",entity_id:inv.id,related_type:"square_payment",related_id:paymentId,source:"square_webhook",priority:"high",read:false});return json({ok:true,requires_review:true});}
 const paidAt=String(payment?.created_at||new Date().toISOString()); const {data:recorded,error:recordErr}=await admin.rpc("record_square_payment_from_webhook",{p_event_id:eventId,p_event_type:eventType,p_merchant_id:merchantId,p_invoice_id:inv.id,p_payment_id:paymentId,p_order_id:orderId,p_paid_at:paidAt,p_applied_amount:base,p_card_fee:fee,p_charged_amount:charged,p_receipt_url:payment?.receipt_url||null,p_card_brand:payment?.card_details?.card?.card_brand||null,p_last4:payment?.card_details?.card?.last_4||null}); if(recordErr)return json({ok:false,error:"Could not record verified payment"},500);
 return json({ok:true,processed:true,invoice_id:inv.id,payment_id:paymentId,receipt_ready:true,result:recorded});
});