/* Owner-configured Ashley routing; business rules and offers are server-owned. */
(function(){
'use strict';
let state=null,loading=false;
const types={spring:'Spring repair',opener:'Openers & controls',installation:'Door installation',repair:'General repair',maintenance:'Maintenance',commercial:'Commercial'};
const factors={profit:'Expected contribution',skill:'Job-type expertise',conversion:'Closing / completion',travel:'Travel time',availability:'Availability',fairness:'Weekly balance'};
const defaults={profit:30,skill:25,conversion:15,travel:15,availability:10,fairness:5};
const e=x=>esc(String(x??'')),arg=x=>e(JSON.stringify(String(x)));
const api=async body=>{
 const {data,error}=await SB.functions.invoke('ashley-dispatch',{body});
 if(error||!data?.ok){let detail=data?.error;if(!detail&&error?.context?.json){try{detail=(await error.context.json()).error;}catch{}}throw Error(detail||error?.message||'Ashley routing is unavailable.');}
 return data;
};
const owner=()=>CURRENT_TEAM_MEMBER?.role==='owner'&&!VIEW_AS;
const profile=id=>state?.profiles?.find(p=>p.technician_id===id)?.profile;
const numeric=(v,min,max)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
function setupChecks(t){
 const p=profile(t.id)||{},jobs=Object.entries(p.specialties||{}),days=Object.entries(p.shifts||{}),zips=Object.entries(p.travelMinutesByZip||{});
 return [
  {label:'App login linked',ok:!!t.authUserId},
  {label:'Active technician',ok:String(t.status).toLowerCase()==='active'},
  {label:'Job types & business estimates',ok:jobs.length>0&&jobs.every(([type,v])=>types[type]&&v&&numeric(v.skill,1,5)&&numeric(v.closeRate,0,100)&&numeric(v.averageTicket,0,50000)&&numeric(v.durationMinutes,15,1440)&&numeric(v.materialCost,0,50000))},
  {label:'Working days & hours',ok:days.length>0&&days.every(([day,v])=>/^[0-6]$/.test(day)&&Array.isArray(v)&&v.length===2&&v.every(Number.isInteger)&&v[0]>=0&&v[1]<=1440&&v[1]>v[0])},
  {label:'Service ZIPs & travel',ok:zips.length>0&&zips.length<=300&&zips.every(([zip,v])=>/^\d{5}$/.test(zip)&&numeric(v,0,240))},
  {label:'Capacity, costs & commission',ok:Number.isInteger(p.dailyLimit)&&numeric(p.dailyLimit,1,30)&&numeric(p.hourlyCost,0,1000)&&numeric(p.commissionPercent,0,100)},
  {label:'Included in routing',ok:p.enabled===true}
 ];
}
const isReady=t=>setupChecks(t).every(c=>c.ok);
function technicianHtml(t){
 const p=profile(t.id),checks=setupChecks(t),missing=checks.filter(c=>!c.ok),wa=whatsappRecipientState(t);
 const waText=t.notifyPrefs?.newLead===false?'WhatsApp lead alerts off':wa.ready?'WhatsApp recipient details saved':!normalizeToE164(t.whatsappNumber)?'WhatsApp number needed':'WhatsApp opt-in needed';
 return `<article class="ashley-setup"><div class="ashley-tech"><div class="ashley-person" aria-hidden="true">🧑‍🔧</div><div><b>${e(t.name)}</b><span>${missing.length?missing.length+' setup steps remaining':'Ready for routing'}</span><small>${e(Object.keys(p?.specialties||{}).map(k=>types[k]).filter(Boolean).join(' · ')||'Choose the work this technician handles')}</small></div>${owner()?`<button class="btn btn-sm" onclick="Ashley.editProfile(${arg(t.id)})">${p?'Edit profile':'Set up profile'}</button>`:''}</div>
 <ul class="ashley-checks">${checks.map(c=>`<li class="${c.ok?'complete':'incomplete'}"><span aria-label="${c.ok?'Complete':'Needed'}">${c.ok?'✓':'○'}</span> ${e(c.label)}</li>`).join('')}</ul>
 <div class="ashley-contact-state">${normalizeToE164(t.phone)?'SMS number saved':'SMS number needed'} · ${e(waText)}</div>
 ${owner()?`<div class="dispatch-actions ashley-setup-actions"><button class="btn btn-sm" onclick="Ashley.login(${arg(t.id)})">${t.authUserId?'Manage login':'Create login'}</button><button class="btn btn-sm" onclick="Ashley.contacts(${arg(t.id)})">Contact & alerts${String(t.status).toLowerCase()==='active'?'':' · Set active status'}</button></div>`:''}</article>`;
}
function requiredNumber(id){
 const field=document.getElementById(id);
 if(!field||!field.value.trim()||!field.checkValidity()){field?.reportValidity();field?.focus();throw Error('Complete the highlighted field with a valid number.');}
 return Number(field.value);
}
async function load(){if(loading)return;loading=true;try{state=await api({action:'state'});if(['receptionist','ai_manager'].includes(route.page)&&receptionistState.subview==='routing')panel(document.getElementById('receptionistBody'));}catch(err){const body=document.getElementById('receptionistBody');if(body&&receptionistState.subview==='routing')body.innerHTML=`<div class="dispatch-notice">${e(err.message)} <button class="btn btn-sm" onclick="Ashley.refresh()">Try again</button></div>`;}finally{loading=false;}}
function panel(body){
 if(!body)return;if(!state){body.innerHTML='<div class="dispatch-notice">Loading Ashley’s routing settings…</div>';load();return;}
 const p=state.policy,c=p.config,techs=STORE.team.filter(t=>String(t.role).toLowerCase()==='technician'&&!t.archivedAt),ready=techs.filter(isReady).length;
 body.innerHTML=`<div class="ashley-hero"><div class="ashley-avatar" aria-hidden="true">✨</div><div><div class="dispatch-meta">ASHLEY · SMART DISPATCH</div><h2>The right fit for each lead</h2><p>Business value first. Skills, travel and workload considered together.</p></div><span class="ashley-mode">${{off:'Paused',recommend:'Recommendations',automatic:'Automatic'}[p.mode]}</span></div>
 ${state.paused?'<div class="dispatch-notice">AI Manager is paused. You can preview matches; automatic offers remain paused until AI Manager is resumed.</div>':''}<div class="ashley-columns"><section class="dispatch-card"><h3>🎯 How Ashley decides</h3><p>Only eligible technicians are ranked. Weekly balance helps when the business scores are close.</p><div class="field"><span class="lbl">Ashley dispatch mode</span><div role="group" aria-label="Ashley dispatch mode" style="display:flex;gap:8px;flex-wrap:wrap"><button type="button" class="btn ${p.mode==='automatic'?'btn-primary':''}" aria-pressed="${p.mode==='automatic'}" ${!owner()||!ready?'disabled':''} onclick="Ashley.setMode('automatic',this)">⚡ Automatic</button><button type="button" class="btn ${p.mode!=='automatic'?'btn-primary':''}" aria-pressed="${p.mode!=='automatic'}" ${!owner()?'disabled':''} onclick="Ashley.setMode('recommend',this)">👤 Manual</button></div><p class="dispatch-subtle">${p.mode==='automatic'?'Ashley selects a technician and sends eligible new Ashley lead offers automatically.':'Ashley recommends a technician. The office sends the offer.'}</p><select id="ashleyMode" hidden aria-hidden="true"><option value="off" ${p.mode==='off'?'selected':''}>Paused</option><option value="recommend" ${p.mode==='recommend'?'selected':''}>Manual</option><option value="automatic" ${!ready&&p.mode!=='automatic'?'disabled':''} ${p.mode==='automatic'?'selected':''}>Automatic</option></select></div>${!ready?'<p class="ashley-setup-hint">Complete at least one technician’s login and routing profile to enable automatic offers.</p>':''}<div class="ashley-mini-grid"><label class="field"><span class="lbl">Minimum score</span><input id="ashleyMin" type="number" min="0" max="100" value="${c.minScore}"></label><label class="field"><span class="lbl">Max travel · minutes</span><input id="ashleyTravel" type="number" min="1" max="240" value="${c.maxTravelMinutes}"></label><label class="field"><span class="lbl">Offer attempts</span><input id="ashleyAttempts" type="number" min="1" max="10" value="${c.maxAttempts}"></label><label class="field"><span class="lbl">Between-job buffer · min</span><input id="ashleyBuffer" type="number" min="0" max="120" value="${c.bufferMinutes}"></label></div>
 <details class="ashley-details"><summary>Adjust priorities & business costs</summary><div class="ashley-weights">${Object.entries(factors).map(([k,label])=>`<label><span>${label}</span><input id="ashleyWeight_${k}" type="number" min="0" max="100" value="${c.weights[k]??defaults[k]}"></label>`).join('')}</div><div class="ashley-mini-grid"><label class="field"><span class="lbl">Balance within score gap</span><input id="ashleyTolerance" type="number" min="0" max="20" value="${c.fairnessTolerance}"></label><label class="field"><span class="lbl">Contribution target · $</span><input id="ashleyProfit" type="number" min="1" value="${c.profitTarget}"></label><label class="field"><span class="lbl">Travel cost · $/minute</span><input id="ashleyCost" type="number" min="0" max="20" step="0.1" value="${c.travelCostPerMinute}"></label><label class="field"><span class="lbl">Business timezone</span><input id="ashleyTimezone" value="${e(c.timezone)}"></label></div><p class="dispatch-subtle">Weekly balance is capped at 20% of the total. A lower workload cannot override missing skills, working hours or an unprofitable job.</p></details>${owner()?'<button class="btn btn-primary" onclick="Ashley.savePolicy(this)">Save routing settings</button>':''}<div class="dispatch-subtle">An unanswered offer expires after five minutes. Ashley then tries the next eligible technician, up to your attempt limit.</div></section>
 <section class="dispatch-card"><h3>👥 Your technicians <span class="ashley-count">${ready} / ${techs.length} ready</span></h3><p>Complete the setup below for each technician. Only saved business estimates are used.</p><div class="ashley-tech-list">${techs.map(technicianHtml).join('')||'<p>Add technicians in Team to get started.</p>'}</div><div class="dispatch-notice" style="margin-top:16px">📍 Travel uses your ZIP-based estimates. These are planning estimates, not live traffic or GPS.</div><p class="dispatch-subtle">Phone alerts must be enabled on each technician’s device. WhatsApp also requires the Meta connection and an approved template; saved recipient details alone do not confirm delivery.</p><button class="btn" onclick="go(\'team\')">Open Team →</button></section></div>
 <section class="dispatch-card ashley-preview"><div><h3>🔎 Preview a match</h3><p>See the ranking and the reason behind every choice.</p></div><div class="dispatch-actions"><select id="ashleyLead" aria-label="Lead to preview"><option value="">Choose a lead</option>${STORE.leads.filter(l=>!l.assignedTechnicianId&&!['lost','cancelled'].includes(l.status)).map(l=>`<option value="${e(l.id)}">${e(l.name)} · ${e(l.zip||'ZIP needed')}</option>`).join('')}</select><button class="btn btn-primary" onclick="Ashley.preview(this)">Compare technicians</button></div><div id="ashleyPreviewResult"></div></section>
 <section class="dispatch-card" style="margin-top:16px"><h3>🪄 Recent decisions</h3>${state.decisions.length?state.decisions.map(d=>`<div class="dispatch-row"><div><b>${d.status==='offered'?'Offer created for '+e(d.decision?.winner?.name||'technician'):'Waiting for a match'}</b><div class="dispatch-subtle">ZIP ${e(d.decision?.zip||'—')} · ${e(d.decision?.reason||'')}</div></div><span class="dispatch-subtle">${new Date(d.created_at).toLocaleString()}</span></div>`).join(''):'<p class="dispatch-subtle">Automatic decisions appear here with their explanation. Existing leads stay under office control when automatic routing is first enabled.</p>'}</section>`;
}
function previewHtml(d){return `<div class="dispatch-notice">${d.winner?'✨ Recommended: <b>'+e(d.winner.name)+'</b> · '+d.winner.score+'/100':'⏳ No offer yet'}<div class="dispatch-subtle">${e(d.reason)}</div></div>${(d.candidates||[]).map(c=>`<details class="ashley-candidate ${c.eligible?'':'unavailable'}"><summary><span><b>${e(c.name)}</b><small>${c.eligible?`${c.travelMinutes} min travel · ${c.weeklyJobs} jobs this week`:e(c.excluded.join(' · '))}</small></span><strong>${c.eligible?c.score+'/100':'Not eligible'}</strong></summary><div class="ashley-candidate-detail"><div class="ashley-score-grid">${Object.entries(c.features||{}).map(([k,v])=>`<div><span>${factors[k]}</span><b>${Math.round(v)}/100</b></div>`).join('')}</div><ul>${c.reasons.map(r=>`<li>${e(r)}</li>`).join('')}</ul><p>${c.fairnessApplied?'Weekly balance contributed within the business tolerance.':'Business fit takes priority over weekly balance.'}</p></div></details>`).join('')}`;}
window.Ashley={
 async setMode(mode,button){if(!owner())return;document.getElementById('ashleyMode').value=mode;await this.savePolicy(button);},
 open(){receptionistState.subview='routing';go('receptionist');},refresh(){state=null;load();},
 login(id){if(owner())openTeamLoginAccess(id);},
 contacts(id){if(owner())openTeamModal(id);},
 async savePolicy(button){if(!owner())return;button.disabled=true;try{const config={...state.policy.config,weights:Object.fromEntries(Object.keys(factors).map(k=>[k,+document.getElementById('ashleyWeight_'+k).value]))};for(const [key,id] of Object.entries({minScore:'Min',maxTravelMinutes:'Travel',maxAttempts:'Attempts',bufferMinutes:'Buffer',fairnessTolerance:'Tolerance',profitTarget:'Profit',travelCostPerMinute:'Cost'}))config[key]=+document.getElementById('ashley'+id).value;config.timezone=document.getElementById('ashleyTimezone').value.trim();await api({action:'save_policy',mode:document.getElementById('ashleyMode').value,config});toast('Ashley routing settings saved');await load();}catch(err){toast(err.message,true);}finally{button.disabled=false;}},
 async preview(button){const id=document.getElementById('ashleyLead').value;if(!id)return toast('Choose a lead first',true);button.disabled=true;try{const data=await api({action:'preview',lead_id:id});document.getElementById('ashleyPreviewResult').innerHTML=previewHtml(data.decision);}catch(err){toast(err.message,true);}finally{button.disabled=false;}},
 async match(id){try{const data=await api({action:'preview',lead_id:id});showModal({title:'✨ Ashley’s technician match',body:previewHtml(data.decision)});document.getElementById('modalSaveBtn').style.display='none';}catch(err){toast(err.message,true);}},
 editProfile(id){if(!owner())return;const t=STORE.team.find(t=>t.id===id),p=profile(id)||{enabled:false,dailyLimit:'',hourlyCost:'',commissionPercent:t?.commissionPercent??30,shifts:{},specialties:{},travelMinutesByZip:{}};const time=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
 showModal({title:'🧑‍🔧 '+e(t?.name||'Technician')+' · Routing profile',wide:true,body:`<label class="ashley-toggle"><input id="apEnabled" type="checkbox" ${p.enabled?'checked':''}> Include this technician in automatic routing</label><div class="ashley-mini-grid"><label class="field"><span class="lbl">Daily job limit</span><input id="apLimit" type="number" required min="1" max="30" step="1" value="${p.dailyLimit}"></label><label class="field"><span class="lbl">Additional labor cost · $/hour</span><input id="apHourly" type="number" required min="0" max="1000" step="0.01" value="${p.hourlyCost}"></label></div><label class="field"><span class="lbl">Commission on sale less parts · %</span><input id="apCommission" type="number" required min="0" max="100" step="0.1" value="${p.commissionPercent??t?.commissionPercent??30}"></label><h4>🛠️ Job types & business estimates</h4><p class="dispatch-subtle">Select the work this technician handles and enter your estimates. Zero is allowed where it applies. Recent outcomes gradually refine these estimates.</p>${Object.entries(types).map(([key,label])=>{const v=p.specialties?.[key]||{};return `<details class="ashley-skill" ${p.specialties?.[key]?'open':''}><summary>${label}</summary><label class="ashley-toggle"><input id="ap_${key}" type="checkbox" ${p.specialties?.[key]?'checked':''}> Can handle ${label.toLowerCase()}</label><div class="ashley-mini-grid">${[['skill','Expertise · 1–5',1,5],['closeRate','Expected closing rate · %',0,100],['averageTicket','Average sale before tax · $',0,50000],['durationMinutes','Typical work time · min',15,1440],['materialCost','Typical materials · $',0,50000]].map(([k,name,min,max])=>`<label class="field"><span class="lbl">${name}</span><input type="number" required id="ap_${key}_${k}" min="${min}" max="${max}" step="${k==='durationMinutes'?1:0.01}" value="${e(v[k]??'')}"></label>`).join('')}</div></details>`;}).join('')}<h4>📍 Service ZIPs & typical drive time</h4><label class="field"><span class="lbl">One ZIP and travel time per line, e.g. 01757=20</span><textarea id="apZips" rows="4" placeholder="01757=20&#10;01748=35">${e(Object.entries(p.travelMinutesByZip).map(([z,m])=>z+'='+m).join('\n'))}</textarea></label><details class="ashley-details" open><summary>🕒 Working days & hours</summary>${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,i)=>`<div class="ashley-hours"><label><input id="apDay_${i}" type="checkbox" ${p.shifts[i]?'checked':''}> ${day}</label><input aria-label="${day} start" id="apStart_${i}" type="time" value="${time(p.shifts[i]?.[0]??480)}"><span>to</span><input aria-label="${day} end" id="apEnd_${i}" type="time" value="${time(p.shifts[i]?.[1]??1080)}"></div>`).join('')}</details>`,onSave:async()=>{
 try{
 const specialties={},shifts={},travelMinutesByZip={};
 for(const key of Object.keys(types))if(document.getElementById('ap_'+key).checked){
  specialties[key]={};
  for(const k of ['skill','closeRate','averageTicket','durationMinutes','materialCost'])specialties[key][k]=requiredNumber('ap_'+key+'_'+k);
 }
 for(let i=0;i<7;i++)if(document.getElementById('apDay_'+i).checked){
  const fields=['Start','End'].map(k=>document.getElementById('ap'+k+'_'+i));
  if(fields.some(f=>!/^\d{2}:\d{2}$/.test(f.value)))throw Error('Enter a start and end time for each working day.');
  shifts[i]=fields.map(f=>{const [h,m]=f.value.split(':').map(Number);return h*60+m;});
  if(shifts[i][1]<=shifts[i][0])throw Error('Working hours must end after they start.');
 }
 for(const line of document.getElementById('apZips').value.trim().split(/\n|,/).filter(x=>x.trim())){
  const m=line.trim().match(/^(\d{5})\s*[=:]\s*(\d+(?:\.\d+)?)$/);
  if(!m||Number(m[2])>240)throw Error('Use ZIP=minutes, from 0 to 240 minutes, one service area per line.');
  if(Object.hasOwn(travelMinutesByZip,m[1]))throw Error('Enter each service ZIP only once.');
  travelMinutesByZip[m[1]]=Number(m[2]);
 }
 if(Object.keys(travelMinutesByZip).length>300)throw Error('Use no more than 300 service ZIPs per technician.');
 const enabled=document.getElementById('apEnabled').checked;
 if(enabled&&(!Object.keys(specialties).length||!Object.keys(shifts).length||!Object.keys(travelMinutesByZip).length))throw Error('Add job types, working hours and service ZIPs before including this technician in routing.');
 await api({action:'save_profile',technician_id:id,profile:{enabled,dailyLimit:requiredNumber('apLimit'),hourlyCost:requiredNumber('apHourly'),commissionPercent:requiredNumber('apCommission'),specialties,shifts,travelMinutesByZip}});
 closeModal();toast('Technician routing profile saved');await load();
 }catch(err){toast(err.message,true);}

 }});
 }
};
const baseReceptionist=renderAiReceptionist;
renderAiReceptionist=function(content,actions){baseReceptionist(content,actions);if(!IS_OWNER)return;const tabs=content.querySelector('.doc-tabbar');if(tabs&&!tabs.querySelector('[data-ashley-tab]'))tabs.insertAdjacentHTML('beforeend',`<button class="doc-tab ${receptionistState.subview==='routing'?'active':''}" data-ashley-tab onclick="Ashley.open()">✨ Smart dispatch</button>`);if(receptionistState.subview==='routing')panel(document.getElementById('receptionistBody'));};
const baseTeam=renderTeam;renderTeam=function(content,actions){baseTeam(content,actions);if(owner())actions.insertAdjacentHTML('beforeend','<button class="btn" onclick="Ashley.open()">✨ Ashley routing</button>');};
const baseLeads=renderLeads;renderLeads=function(content,actions){baseLeads(content,actions);if(!isTechnicianView()&&['owner','admin','dispatcher'].includes(CURRENT_TEAM_MEMBER?.role))content.querySelectorAll('.dispatch-row').forEach(row=>{const button=row.querySelector('button[onclick^="Dispatch.offer("]');if(button){const match=button.getAttribute('onclick').match(/Dispatch\.offer\((.*)\)/);if(match)row.querySelector('.dispatch-actions')?.insertAdjacentHTML('beforeend',`<button class="btn btn-sm" onclick="Ashley.match(${e(match[1])})">✨ Compare techs</button>`);}});};
})();
