/* Owner-configured Ashley routing; business rules and offers are server-owned. */
(function(){
'use strict';
let state=null,loading=false;
const types={spring:'Spring repair',opener:'Openers & controls',installation:'Door installation',repair:'General repair',maintenance:'Maintenance',commercial:'Commercial'};
const factors={profit:'Expected contribution',skill:'Job-type expertise',conversion:'Closing / completion',travel:'Travel time',availability:'Availability',fairness:'Weekly balance'};
const defaults={profit:30,skill:25,conversion:15,travel:15,availability:10,fairness:5};
const e=x=>esc(String(x??'')),arg=x=>e(JSON.stringify(String(x)));
const api=async body=>{const {data,error}=await SB.functions.invoke('ashley-dispatch',{body});if(error||!data?.ok)throw Error(data?.error||error?.message||'Ashley routing is unavailable.');return data;};
const owner=()=>CURRENT_TEAM_MEMBER?.role==='owner'&&!VIEW_AS;
const profile=id=>state?.profiles?.find(p=>p.technician_id===id)?.profile;
async function load(){if(loading)return;loading=true;try{state=await api({action:'state'});if(['receptionist','ai_manager'].includes(route.page)&&receptionistState.subview==='routing')panel(document.getElementById('receptionistBody'));}catch(err){const body=document.getElementById('receptionistBody');if(body&&receptionistState.subview==='routing')body.innerHTML=`<div class="dispatch-notice">${e(err.message)} <button class="btn btn-sm" onclick="Ashley.refresh()">Try again</button></div>`;}finally{loading=false;}}
function panel(body){
 if(!body)return;if(!state){body.innerHTML='<div class="dispatch-notice">Loading Ashley’s routing settings…</div>';load();return;}
 const p=state.policy,c=p.config,techs=STORE.team.filter(t=>String(t.role).toLowerCase()==='technician'),ready=techs.filter(t=>profile(t.id)?.enabled&&t.authUserId&&t.status==='Active').length;
 body.innerHTML=`<div class="ashley-hero"><div class="ashley-avatar" aria-hidden="true">✨</div><div><div class="dispatch-meta">ASHLEY · SMART DISPATCH</div><h2>The right fit for each lead</h2><p>Business value first. Skills, travel and workload considered together.</p></div><span class="ashley-mode">${{off:'Paused',recommend:'Recommendations',automatic:'Automatic'}[p.mode]}</span></div>
 ${state.paused?'<div class="dispatch-notice">AI Manager is paused. You can preview matches; automatic offers remain paused until AI Manager is resumed.</div>':''}<div class="ashley-columns"><section class="dispatch-card"><h3>🎯 How Ashley decides</h3><p>Only eligible technicians are ranked. Weekly balance helps when the business scores are close.</p><label class="field"><span class="lbl">Routing mode</span><select id="ashleyMode" ${owner()?'':'disabled'}><option value="off" ${p.mode==='off'?'selected':''}>Paused</option><option value="recommend" ${p.mode==='recommend'?'selected':''}>Recommendations only</option><option value="automatic" ${p.mode==='automatic'?'selected':''}>Automatic offers from new Ashley leads</option></select></label><div class="ashley-mini-grid"><label class="field"><span class="lbl">Minimum score</span><input id="ashleyMin" type="number" min="0" max="100" value="${c.minScore}"></label><label class="field"><span class="lbl">Max travel · minutes</span><input id="ashleyTravel" type="number" min="1" max="240" value="${c.maxTravelMinutes}"></label><label class="field"><span class="lbl">Offer attempts</span><input id="ashleyAttempts" type="number" min="1" max="10" value="${c.maxAttempts}"></label><label class="field"><span class="lbl">Between-job buffer · min</span><input id="ashleyBuffer" type="number" min="0" max="120" value="${c.bufferMinutes}"></label></div>
 <details class="ashley-details"><summary>Adjust priorities & business costs</summary><div class="ashley-weights">${Object.entries(factors).map(([k,label])=>`<label><span>${label}</span><input id="ashleyWeight_${k}" type="number" min="0" max="100" value="${c.weights[k]??defaults[k]}"></label>`).join('')}</div><div class="ashley-mini-grid"><label class="field"><span class="lbl">Balance within score gap</span><input id="ashleyTolerance" type="number" min="0" max="20" value="${c.fairnessTolerance}"></label><label class="field"><span class="lbl">Contribution target · $</span><input id="ashleyProfit" type="number" min="1" value="${c.profitTarget}"></label><label class="field"><span class="lbl">Travel cost · $/minute</span><input id="ashleyCost" type="number" min="0" max="20" step="0.1" value="${c.travelCostPerMinute}"></label><label class="field"><span class="lbl">Business timezone</span><input id="ashleyTimezone" value="${e(c.timezone)}"></label></div><p class="dispatch-subtle">Weekly balance is capped at 20% of the total. A lower workload cannot override missing skills, working hours or an unprofitable job.</p></details>${owner()?'<button class="btn btn-primary" onclick="Ashley.savePolicy(this)">Save routing settings</button>':''}<div class="dispatch-subtle">An unanswered offer expires after five minutes. Ashley then tries the next eligible technician, up to your attempt limit.</div></section>
 <section class="dispatch-card"><h3>👥 Your technicians <span class="ashley-count">${ready} ready</span></h3><p>Set each technician’s strengths, hours and service areas.</p><div class="ashley-tech-list">${techs.map(t=>{const pr=profile(t.id),on=pr?.enabled&&t.authUserId&&t.status==='Active';return `<div class="ashley-tech"><div class="ashley-person" aria-hidden="true">🧑‍🔧</div><div><b>${e(t.name)}</b><span>${on?'Ready for routing':!t.authUserId?'App login needed':'Complete routing profile'}</span><small>${pr?Object.keys(pr.specialties||{}).map(k=>types[k]).join(' · '):'Job types, travel and pricing'}</small></div>${owner()?`<button class="btn btn-sm" onclick="Ashley.editProfile(${arg(t.id)})">${pr?'Edit':'Set up'}</button>`:''}</div>`;}).join('')||'<p>Add technicians in Team to get started.</p>'}</div><div class="dispatch-notice" style="margin-top:16px">📍 Travel uses your ZIP-based estimates. These are planning estimates, not live traffic or GPS.</div><button class="btn" onclick="go(\'team\')">Open Team →</button></section></div>
 <section class="dispatch-card ashley-preview"><div><h3>🔎 Preview a match</h3><p>See the ranking and the reason behind every choice.</p></div><div class="dispatch-actions"><select id="ashleyLead" aria-label="Lead to preview"><option value="">Choose a lead</option>${STORE.leads.filter(l=>!l.assignedTechnicianId&&!['lost','cancelled'].includes(l.status)).map(l=>`<option value="${e(l.id)}">${e(l.name)} · ${e(l.zip||'ZIP needed')}</option>`).join('')}</select><button class="btn btn-primary" onclick="Ashley.preview(this)">Compare technicians</button></div><div id="ashleyPreviewResult"></div></section>
 <section class="dispatch-card" style="margin-top:16px"><h3>🪄 Recent decisions</h3>${state.decisions.length?state.decisions.map(d=>`<div class="dispatch-row"><div><b>${d.status==='offered'?'Offer created for '+e(d.decision?.winner?.name||'technician'):'Waiting for a match'}</b><div class="dispatch-subtle">ZIP ${e(d.decision?.zip||'—')} · ${e(d.decision?.reason||'')}</div></div><span class="dispatch-subtle">${new Date(d.created_at).toLocaleString()}</span></div>`).join(''):'<p class="dispatch-subtle">Automatic decisions appear here with their explanation. Existing leads stay under office control when automatic routing is first enabled.</p>'}</section>`;
}
function previewHtml(d){return `<div class="dispatch-notice">${d.winner?'✨ Recommended: <b>'+e(d.winner.name)+'</b> · '+d.winner.score+'/100':'⏳ No offer yet'}<div class="dispatch-subtle">${e(d.reason)}</div></div>${(d.candidates||[]).map(c=>`<details class="ashley-candidate ${c.eligible?'':'unavailable'}"><summary><span><b>${e(c.name)}</b><small>${c.eligible?`${c.travelMinutes} min travel · ${c.weeklyJobs} jobs this week`:e(c.excluded.join(' · '))}</small></span><strong>${c.eligible?c.score+'/100':'Not eligible'}</strong></summary><div class="ashley-candidate-detail"><div class="ashley-score-grid">${Object.entries(c.features||{}).map(([k,v])=>`<div><span>${factors[k]}</span><b>${Math.round(v)}/100</b></div>`).join('')}</div><ul>${c.reasons.map(r=>`<li>${e(r)}</li>`).join('')}</ul><p>${c.fairnessApplied?'Weekly balance contributed within the business tolerance.':'Business fit takes priority over weekly balance.'}</p></div></details>`).join('')}`;}
window.Ashley={
 open(){receptionistState.subview='routing';go('receptionist');},refresh(){state=null;load();},
 async savePolicy(button){if(!owner())return;button.disabled=true;try{const config={...state.policy.config,weights:Object.fromEntries(Object.keys(factors).map(k=>[k,+document.getElementById('ashleyWeight_'+k).value]))};for(const [key,id] of Object.entries({minScore:'Min',maxTravelMinutes:'Travel',maxAttempts:'Attempts',bufferMinutes:'Buffer',fairnessTolerance:'Tolerance',profitTarget:'Profit',travelCostPerMinute:'Cost'}))config[key]=+document.getElementById('ashley'+id).value;config.timezone=document.getElementById('ashleyTimezone').value.trim();await api({action:'save_policy',mode:document.getElementById('ashleyMode').value,config});toast('Ashley routing settings saved');await load();}catch(err){toast(err.message,true);}finally{button.disabled=false;}},
 async preview(button){const id=document.getElementById('ashleyLead').value;if(!id)return toast('Choose a lead first',true);button.disabled=true;try{const data=await api({action:'preview',lead_id:id});document.getElementById('ashleyPreviewResult').innerHTML=previewHtml(data.decision);}catch(err){toast(err.message,true);}finally{button.disabled=false;}},
 async match(id){try{const data=await api({action:'preview',lead_id:id});showModal({title:'✨ Ashley’s technician match',body:previewHtml(data.decision)});document.getElementById('modalSaveBtn').style.display='none';}catch(err){toast(err.message,true);}},
 editProfile(id){if(!owner())return;const t=STORE.team.find(t=>t.id===id),p=profile(id)||{enabled:false,dailyLimit:4,hourlyCost:0,commissionPercent:t?.commissionPercent??30,shifts:{1:[480,1080],2:[480,1080],3:[480,1080],4:[480,1080],5:[480,1080]},specialties:{},travelMinutesByZip:{}};const time=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
 showModal({title:'🧑‍🔧 '+(t?.name||'Technician')+' · Routing profile',body:`<label class="ashley-toggle"><input id="apEnabled" type="checkbox" ${p.enabled?'checked':''}> Include this technician in automatic routing</label><div class="ashley-mini-grid"><label class="field"><span class="lbl">Daily job limit</span><input id="apLimit" type="number" min="1" max="30" value="${p.dailyLimit}"></label><label class="field"><span class="lbl">Additional labor cost · $/hour</span><input id="apHourly" type="number" min="0" value="${p.hourlyCost}"></label></div><label class="field"><span class="lbl">Commission on sale less parts · %</span><input id="apCommission" type="number" min="0" max="100" value="${p.commissionPercent??t?.commissionPercent??30}"></label><h4>🛠️ Job types & business estimates</h4><p class="dispatch-subtle">Enable only the jobs this technician handles. Edit the starting values to match your business. Recent outcomes gradually refine these estimates.</p>${Object.entries(types).map(([key,label])=>{const v=p.specialties[key]||{skill:3,closeRate:60,averageTicket:300,durationMinutes:90,materialCost:80};return `<details class="ashley-skill" ${p.specialties[key]?'open':''}><summary>${label}</summary><label class="ashley-toggle"><input id="ap_${key}" type="checkbox" ${p.specialties[key]?'checked':''}> Can handle ${label.toLowerCase()}</label><div class="ashley-mini-grid">${[['skill','Expertise · 1–5',1,5],['closeRate','Expected closing rate · %',0,100],['averageTicket','Average sale before tax · $',0,50000],['durationMinutes','Typical work time · min',15,1440],['materialCost','Typical materials · $',0,50000]].map(([k,name,min,max])=>`<label class="field"><span class="lbl">${name}</span><input type="number" id="ap_${key}_${k}" min="${min}" max="${max}" value="${v[k]}"></label>`).join('')}</div></details>`;}).join('')}<h4>📍 Service ZIPs & typical drive time</h4><label class="field"><span class="lbl">One ZIP and travel time per line, e.g. 01757=20</span><textarea id="apZips" rows="4" placeholder="01757=20&#10;01748=35">${e(Object.entries(p.travelMinutesByZip).map(([z,m])=>z+'='+m).join('\n'))}</textarea></label><details class="ashley-details"><summary>🕒 Working days & hours</summary>${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,i)=>`<div class="ashley-hours"><label><input id="apDay_${i}" type="checkbox" ${p.shifts[i]?'checked':''}> ${day}</label><input aria-label="${day} start" id="apStart_${i}" type="time" value="${time(p.shifts[i]?.[0]??480)}"><span>to</span><input aria-label="${day} end" id="apEnd_${i}" type="time" value="${time(p.shifts[i]?.[1]??1080)}"></div>`).join('')}</details>`,onSave:async()=>{
 const specialties={},shifts={},travelMinutesByZip={};for(const key of Object.keys(types))if(document.getElementById('ap_'+key).checked){specialties[key]={};for(const k of ['skill','closeRate','averageTicket','durationMinutes','materialCost'])specialties[key][k]=+document.getElementById('ap_'+key+'_'+k).value;}
 for(let i=0;i<7;i++)if(document.getElementById('apDay_'+i).checked)shifts[i]=['Start','End'].map(k=>{const [h,m]=document.getElementById('ap'+k+'_'+i).value.split(':').map(Number);return h*60+m;});
 for(const line of document.getElementById('apZips').value.trim().split(/\n|,/).filter(x=>x.trim())){const m=line.trim().match(/^(\d{5})\s*[=:]\s*(\d+(?:\.\d+)?)$/);if(!m)return toast('Use ZIP=minutes, one service area per line.',true);travelMinutesByZip[m[1]]=+m[2];}
 try{await api({action:'save_profile',technician_id:id,profile:{enabled:document.getElementById('apEnabled').checked,dailyLimit:+document.getElementById('apLimit').value,hourlyCost:+document.getElementById('apHourly').value,commissionPercent:+document.getElementById('apCommission').value,specialties,shifts,travelMinutesByZip}});closeModal();toast('Technician routing profile saved');await load();}catch(err){toast(err.message,true);}
 }});
 }
};
const baseReceptionist=renderAiReceptionist;
renderAiReceptionist=function(content,actions){baseReceptionist(content,actions);if(!IS_OWNER)return;const tabs=content.querySelector('.doc-tabbar');if(tabs&&!tabs.querySelector('[data-ashley-tab]'))tabs.insertAdjacentHTML('beforeend',`<button class="doc-tab ${receptionistState.subview==='routing'?'active':''}" data-ashley-tab onclick="Ashley.open()">✨ Smart dispatch</button>`);if(receptionistState.subview==='routing')panel(document.getElementById('receptionistBody'));};
const baseTeam=renderTeam;renderTeam=function(content,actions){baseTeam(content,actions);if(owner())actions.insertAdjacentHTML('beforeend','<button class="btn" onclick="Ashley.open()">✨ Ashley routing</button>');};
const baseLeads=renderLeads;renderLeads=function(content,actions){baseLeads(content,actions);if(!isTechnicianView()&&['owner','admin','dispatcher'].includes(CURRENT_TEAM_MEMBER?.role))content.querySelectorAll('.dispatch-row').forEach(row=>{const button=row.querySelector('button[onclick^="Dispatch.offer("]');if(button){const match=button.getAttribute('onclick').match(/Dispatch\.offer\((.*)\)/);if(match)row.querySelector('.dispatch-actions')?.insertAdjacentHTML('beforeend',`<button class="btn btn-sm" onclick="Ashley.match(${e(match[1])})">✨ Compare techs</button>`);}});};
})();
