/* Provider-backed reporting. No CRM wallet or money-transfer simulation. */
(function(){
'use strict';
const state={loaded:false,loading:false,data:null,error:''};
const base=renderWorkspaceHub;
window.BusinessFinance={
 withdraw(){
  if(!IS_OWNER)return;
  showModal({title:'Withdraw to bank · Square',body:'<p>Transfer your available Square balance to the bank account linked in Square.</p><p>Square shows the available amount, destination, transfer options and any fees before you confirm.</p><div class="finance-actions"><a class="btn btn-primary" href="https://app.squareup.com/dashboard/balances" target="_blank" rel="noopener noreferrer">Open Square · Transfer Now</a><button class="btn" onclick="closeModal();BusinessFinance.refresh()">Refresh transfer history</button></div><p class="muted">Complete and confirm the transfer in Square, then return here to refresh its status.</p>'});
 },
 async refresh(){
  if(!IS_OWNER||state.loading)return;state.loading=true;state.error='';if(route.page==='banking')render();
  try{const {data,error}=await SB.functions.invoke('business-finance-status',{body:{}});if(error||!data?.ok)throw new Error(data?.error||'Could not refresh Square bank reporting.');state.data=data;state.loaded=true;}catch(e){state.error=e.message;}finally{state.loading=false;if(route.page==='banking')render();}
 },
 html(){
  const data=state.data||{},banks=data.bank_accounts||[],payouts=data.payouts||[];
  return `<section class="panel finance-connection"><div class="panel-head"><h3>Square deposits & bank connection</h3><button class="btn btn-sm" onclick="BusinessFinance.refresh()" ${state.loading?'disabled':''}>${state.loading?'Checking…':'Refresh status'}</button></div><div class="panel-body pad"><p>Customer card payments are processed by Square and deposited into the bank linked to your Square account. This page shows provider records; it is not a bank balance or a CRM wallet.</p><div class="finance-actions"><a class="btn btn-primary" href="https://app.squareup.com/dashboard/balances/bank-accounts" target="_blank" rel="noopener noreferrer">Connect bank in Square</a><button class="btn btn-primary" onclick="BusinessFinance.withdraw()">Withdraw to bank</button><a class="btn" href="https://squareup.com/help/us/en/article/3896-link-and-edit-your-bank-account" target="_blank" rel="noopener noreferrer">Connection instructions</a><button class="btn" onclick="go('payroll')">Technician payroll</button></div>${state.error?`<p role="alert">${esc(state.error)}</p>`:''}${(data.errors||[]).map(e=>`<p role="alert">${esc(e)}</p>`).join('')}${state.loaded&&!data.configured?'<p>Square reporting credentials are not configured.</p>':''}<div class="finance-bank-list">${banks.map(b=>`<div><b>${esc(b.name)} ···${esc(b.suffix)}</b><span>${esc(b.status)}</span></div>`).join('')||(!state.loading&&state.loaded&&!data.errors?.length?'<p>No linked bank account was returned. Complete the bank connection in Square, then refresh.</p>':'')}</div>${payouts.length?`<h4>Recent Square transfers</h4><div class="workspace-table-scroll"><table class="list"><thead><tr><th>Arrival</th><th>Transfer</th><th>Amount</th><th>Status</th></tr></thead><tbody>${payouts.map(p=>`<tr><td>${esc(p.arrival_date||p.created_at?.slice(0,10)||'—')}</td><td>${esc(p.id)}</td><td>${new Intl.NumberFormat('en-US',{style:'currency',currency:/^[A-Z]{3}$/.test(p.currency)?p.currency:'USD'}).format(p.amount/100)}</td><td>${esc(p.status)}</td></tr>`).join('')}</tbody></table></div><p class="muted">Latest ${payouts.length} transfers${data.has_more?' · More history is available in Square':''}.</p>`:''}<h4>Paying technicians</h4><p>Review the calculated payout in Payroll and export the payroll report. Zelle or bank transfers are completed in Bank of America until a business disbursement provider is connected.</p><div class="finance-actions"><button class="btn" onclick="go('payroll')">Review payroll</button><a class="btn" href="https://www.bankofamerica.com/" target="_blank" rel="noopener noreferrer">Open Bank of America</a></div><p class="muted">No money is moved by these links. A payroll calculation is not a payment confirmation.</p></div></section>`;
 }
};
renderWorkspaceHub=function(content,actions,page){base(content,actions,page);if(page==='banking'&&IS_OWNER){const section=document.createElement('div');section.innerHTML=BusinessFinance.html();content.prepend(section);if(!state.loaded&&!state.loading&&!state.error)queueMicrotask(()=>BusinessFinance.refresh());}};
})();
