(function(){
'use strict';
const U=BusinessToolsUtils,arg=v=>esc(JSON.stringify(String(v||''))),allowed=()=>canOperateOffice()||isTechnicianView();
let origin=null,session=0,busy=false;
function ownTech(){return technicianWorkspaceId();}
function stops(date,tech){return STORE.jobs.filter(j=>!j.deletedAt&&j.scheduledDate===date&&j.technicianId===tech&&!['completed','cancelled','canceled'].includes(j.status)&&(!isTechnicianView()||technicianOwnsJob(j))).map(j=>({id:j.id,job:j,address:j.serviceAddress||getOne('customers',j.customerId)?.address||'',window:calendarWindowMinutes(j.appointmentWindow),point:null}));}
window.DailyRoute={
 open(){if(!allowed())return;session++;busy=false;origin=null;const techs=STORE.team.filter(t=>String(t.role).toLowerCase()==='technician'&&t.status==='active');
  showModal({title:'Technician daily route',wide:true,body:`<p class="muted">Keep appointment windows in order and shorten the distance between stops in the same window. Check the route before traveling; travel time and live traffic are shown in Maps.</p><div class="field-row"><label class="field"><span class="lbl">Service date</span><input type="date" id="routeDate" value="${todayISO()}" onchange="DailyRoute.invalidate()"></label>${isTechnicianView()?`<input type="hidden" id="routeTechnician" value="${esc(ownTech())}">`:`<label class="field"><span class="lbl">Technician</span><select id="routeTechnician" onchange="DailyRoute.invalidate()"><option value="">Select technician</option>${techs.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}</select></label>`}</div><div class="business-tool-controls"><button type="button" class="btn" onclick="DailyRoute.locate()">Use my current location</button><button type="button" class="btn btn-primary" id="routeBuild" onclick="DailyRoute.build()">Build daily route</button></div><p class="muted">US service addresses are located when you build the route. Missing or unmatched addresses need review. Appointments are unchanged.</p><div id="routeStatus" role="status" aria-live="polite"></div><div id="dailyRouteResult"></div>`});
 },
 invalidate(){session++;busy=false;const button=document.getElementById('routeBuild');if(button)button.disabled=false;const result=document.getElementById('dailyRouteResult');if(result)result.innerHTML='';const status=document.getElementById('routeStatus');if(status)status.textContent='Selection changed. Build the route again.';},
 locate(){if(!allowed())return;const status=document.getElementById('routeStatus'),generation=session;if(!status)return;if(!navigator.geolocation){status.textContent='Location is unavailable. You can build the route without a starting point.';return;}status.textContent='Requesting your starting location…';navigator.geolocation.getCurrentPosition(p=>{if(status!==document.getElementById('routeStatus')||generation!==session)return;origin={lat:p.coords.latitude,lng:p.coords.longitude};DailyRoute.invalidate();document.getElementById('routeStatus').textContent='Starting location set. Build the route when ready.';},()=>{if(status===document.getElementById('routeStatus'))status.textContent='Location was unavailable. Build the route without a starting point.';},{timeout:10000,maximumAge:60000});},
 async build(){if(!allowed()||busy)return;const date=document.getElementById('routeDate')?.value,tech=document.getElementById('routeTechnician')?.value,status=document.getElementById('routeStatus'),button=document.getElementById('routeBuild'),result=document.getElementById('dailyRouteResult'),generation=session;if(!U.validDate(date)||!tech)return toast('Choose a service date and technician.',true);if(isTechnicianView()&&tech!==ownTech())return toast('Choose your own route.',true);busy=true;button.disabled=true;status.textContent='Refreshing appointments and locating service addresses…';result.innerHTML='';
  try{await Promise.all([refreshCollection('jobs'),refreshCollection('customers')]);if(generation!==session||status!==document.getElementById('routeStatus')||!allowed())return;const list=stops(date,tech);if(!list.length){status.textContent='No remaining service visits for this date.';return;}if(list.length>20)throw Error('This day has more than 20 visits. Review the schedule before building the route.');
   let warning='';try{const data=await BusinessAssistant.invoke({action:'geocode',job_ids:list.map(s=>s.id)});for(const s of list)s.point=data.locations.find(x=>x.job_id===s.id)?.point||null;}catch(e){warning=e.message+' Appointment order is available below.';}
   if(generation!==session||status!==document.getElementById('routeStatus')||!allowed())return;
   const ordered=U.orderStops(list,origin),missing=ordered.filter(s=>!s.address).length,unmatched=ordered.filter(s=>s.address&&!s.point).length,untimed=ordered.filter(s=>!s.window).length;let overlaps=0;for(let i=0;i<ordered.length;i++)for(let j=i+1;j<ordered.length;j++)if(ordered[i].window&&ordered[j].window&&ordered[i].window[0]<ordered[j].window[1]&&ordered[j].window[0]<ordered[i].window[1])overlaps++;
   const links=missing?[]:U.routeLinks(ordered,origin?origin.lat+','+origin.lng:'');status.textContent=`${ordered.length} stops · ${missing} missing addresses · ${unmatched} unmatched addresses · ${untimed} without a confirmed time window.`;
   result.innerHTML=`${warning?`<p role="alert">${esc(warning)}</p>`:''}${unmatched||untimed?'<p role="note">Review stops that have no located address or confirmed time. Distance ordering applies only within identical windows with all addresses located.</p>':''}${overlaps?`<p role="note">${overlaps} overlapping appointment pair(s). Confirm the schedule and travel time before starting.</p>`:''}${missing?'<p role="alert">Add the missing customer addresses before opening the complete route.</p>':`<div class="business-tool-controls">${links.map(l=>`<a class="btn btn-primary" target="_blank" rel="noopener noreferrer" href="${esc(l.url)}">Open Maps · stops ${l.from}–${l.to}</a>`).join('')}</div>${links.length>1?'<p class="muted">Open each segment in order to include every stop on mobile.</p>':''}`}<div class="business-tool-cards">${ordered.map((s,i)=>`<section class="business-tool-card"><h4>${i+1}. ${esc(s.job.customerName||'Customer')}</h4><p><b>${esc(s.job.appointmentWindow||'Time needs confirmation')}</b> · ${esc(s.job.title||'Service')}</p><p>${esc(s.address||'Missing service address')}${s.address&&!s.point?' · Location needs review':''}</p><div class="business-tool-controls"><button type="button" class="btn" onclick="closeModal();go('jobs',${arg(s.id)})">Open job</button>${s.address?`<a class="btn" target="_blank" rel="noopener noreferrer" href="${esc(U.routeLinks([s])[0].url)}">Navigate to stop</a>`:''}</div></section>`).join('')}</div>`;
  }catch(e){if(generation===session&&status.isConnected)status.textContent=e.message;}finally{if(generation===session){busy=false;if(button.isConnected)button.disabled=false;}}
 }
};
const jobs=renderJobs;renderJobs=function(content,actions){const result=jobs.apply(this,arguments);if(allowed())actions.insertAdjacentHTML('beforeend','<button class="btn" onclick="DailyRoute.open()">Daily route</button>');return result;};
const technician=renderTechnicianDashboard;renderTechnicianDashboard=function(content,actions){const result=technician.apply(this,arguments);if(isTechnicianView())actions.insertAdjacentHTML('beforeend','<button class="btn btn-primary" onclick="DailyRoute.open()">My daily route</button>');return result;};
})();
