/* Contextual drafts are reviewed before they replace any document lines. */
(function(){
'use strict';
let pending=null,session=0;
const paths={wand:'m4 20 12-12m-9 9 3 3M16 2v4m-2-2h4M5 3v4M3 5h4m12 9v4m-2-2h4',calendar:'M4 5h16v16H4zM7 2v6m10-6v6M4 10h16',team:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m18 0v-2a4 4 0 0 0-3-3.87M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8m8-7a4 4 0 0 1 0 8',clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0'};
const icon=key=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[key]||paths.wand}"></path></svg>`;
window.PremiumTools={icon,
 documentMarkup(type,jobId){session++;pending=null;return `<details class="premium-wand" data-wand-type="${type}" data-wand-job="${esc(jobId)}" data-wand-session="${session}"><summary>${icon('wand')} Magic wand · Describe the service</summary><p>Turn technician notes into catalog items and professional wording. Review all quantities and prices before applying.</p><textarea id="wandDescription" rows="3" maxlength="2500" placeholder="Example: Replace two torsion springs, lubricate hinges and test door balance."></textarea><button type="button" class="btn btn-primary" id="wandGenerate" onclick="PremiumTools.generate()">${icon('wand')} Prepare draft</button><div id="wandStatus" role="status" aria-live="polite"></div><div id="wandPreview" class="wand-preview" hidden></div></details>`;},
 async generate(){
  const shell=document.querySelector('[data-wand-type]'),description=document.getElementById('wandDescription')?.value.trim();if(!shell||!description)return toast('Describe the work first.',true);
  const generation=session,button=document.getElementById('wandGenerate'),status=document.getElementById('wandStatus');button.disabled=true;status.textContent='Preparing your service draft…';pending=null;
  try{const {data,error}=await SB.functions.invoke('draft-service-document',{body:{type:shell.dataset.wandType==='quickpay'?'invoice':shell.dataset.wandType,description,job_id:document.getElementById('qpJob')?.value||document.getElementById('f_job')?.value||shell.dataset.wandJob}});let message=data?.error;if(error){try{message=(await error.context.json())?.error||message;}catch{}}if(error||!data?.ok)throw new Error(message||'Could not prepare draft.');if(generation!==session||shell!==document.querySelector('[data-wand-type]'))return;
   pending=data;const preview=document.getElementById('wandPreview');preview.hidden=false;preview.innerHTML=`${data.items.map(x=>`<p><b>${esc(x.desc)}</b> · ${esc(x.qty)} × ${money(x.rate)}<br>${esc(x.details)}</p>`).join('')}${data.notes?`<p>${esc(data.notes)}</p>`:''}${data.warnings.map(x=>`<p role="note">${esc(x)}</p>`).join('')}<button type="button" class="btn btn-primary" onclick="PremiumTools.apply()" ${!data.items.length?'disabled':''}>Apply reviewed draft to line items</button>`;status.textContent='Review the draft below. Applying replaces the current line items; the document remains unsaved.';
  }catch(e){if(shell.isConnected)status.textContent=e.message;}finally{if(button.isConnected)button.disabled=false;}
 },
 apply(){if(!pending?.items?.length)return;const quick=document.querySelector('[data-wand-type]')?.dataset.wandType==='quickpay';if(quick){quickPayLines=JSON.parse(JSON.stringify(pending.items));const notes=document.getElementById('qpNote');if(notes&&pending.notes)notes.value=pending.notes;quickPayRenderLines();updateQuickPayPreview();}else{lineItemsDraft=JSON.parse(JSON.stringify(pending.items));const notes=document.getElementById('f_notes');if(notes&&pending.notes)notes.value=pending.notes;refreshLI();}pending=null;document.getElementById('wandStatus').textContent='Draft applied. Review prices and save the document when ready.';document.getElementById('wandPreview').hidden=true;},
 receipt(){
  if(!canOperateOffice())return;const eligible=STORE.invoices.filter(i=>!i.deletedAt&&invoiceTotal(i)>0&&balanceDue(i)<=0);
  showModal({title:'Magic wand · Receipt',body:`<div class="premium-wand"><p>Choose a paid invoice to generate its receipt from recorded payments.</p><label class="field"><span class="lbl">Paid invoice</span><select id="wandReceiptInvoice">${eligible.map(i=>`<option value="${esc(i.id)}">${esc(i.number||i.id)} · ${esc(i.customerName||'Customer')} · ${money(paidTotal(i))}</option>`).join('')}</select></label><button class="btn btn-primary" onclick="PremiumTools.downloadReceipt()" ${eligible.length?'':'disabled'}>Generate receipt PDF</button>${!eligible.length?'<p>No fully paid invoices are available. Record the customer payment first.</p>':''}</div>`});
 },
 async downloadReceipt(){const id=document.getElementById('wandReceiptInvoice')?.value,inv=getOne('invoices',id);if(!inv||invoiceTotal(inv)<=0||balanceDue(inv)>0)return toast('A fully paid invoice is required.',true);await downloadDocPdf('invoice',id);}
};
const quickOriginal=renderQuickPay;renderQuickPay=function(content,actions){const result=quickOriginal(content,actions);document.getElementById('qpLines')?.insertAdjacentHTML('beforebegin',PremiumTools.documentMarkup('quickpay',''));return result;};
INBOX_EVENT_ICONS.payroll_due=icon('clock');INBOX_EVENT_ICONS.pay_statement_created=icon('wand');INBOX_EVENT_ICONS.technician_payment_recorded=icon('team');
const original=renderPayroll;renderPayroll=function(content,actions){const result=original(content,actions);if(canOperateOffice()){content.insertAdjacentHTML('afterbegin','<p class="muted">The report below projects commission on invoiced work. Open a technician file to settle completed, fully paid jobs and record actual payments.</p>');}if(canOperateOffice())actions.insertAdjacentHTML('afterbegin','<button class="btn btn-primary" onclick="TechnicianPayroll.choose()">Technician file & pay statement</button>');return result;};
const originalExpenses=renderExpenses;renderExpenses=function(content,actions){const result=originalExpenses(content,actions);if(canOperateOffice())actions.insertAdjacentHTML('beforeend','<button class="btn" onclick="PremiumTools.receipt()">'+icon('wand')+' Customer receipt</button>');return result;};
const markup=SocialPostComposer.markup;SocialPostComposer.markup=function(...args){return markup.apply(this,args).replace('AI post assistant',icon('wand')+' Magic wand · Post & image').replace('Generate post & image',icon('wand')+' Generate post & image');};
})();
