/* Pay statements are immutable snapshots; payments are confirmations of external transfers. */
(function(){
'use strict';
let current=null,preview=null,saved=null,history=[],payments=[],busy=false,epoch=0;
const owner=()=>IS_OWNER&&!isTechnicianView();
const arg=x=>esc(JSON.stringify(String(x)));
const dollar=x=>money(Number(x)||0);
const get=id=>document.getElementById(id);
const baseGo=go;go=function(page,id,...args){const result=baseGo(page,id,...args);if(page==='payroll'&&id&&canOperateOffice()&&getOne('team',id))queueMicrotask(()=>TechnicianPayroll.open(id));return result;};window.go=go;
const techs=()=>STORE.team.filter(t=>String(t.role).toLowerCase()==='technician');
function lastWeek(){const end=new Date();end.setDate(end.getDate()-end.getDay());const start=new Date(end);start.setDate(start.getDate()-7);return {from:payrollDateKey(start),to:payrollDateKey(end)};}
async function api(body){const {data,error}=await SB.functions.invoke('technician-payroll',{body});let message=data?.error;if(error){try{message=(await error.context.json())?.error||message;}catch{}}if(error||!data?.ok)throw new Error(message||'Could not load payroll.');return data;}
function fields(){return {technician_id:current.id,from:get('payFrom').value,to:get('payTo').value,rate:Number(get('payRate').value),cash_retained:Number(get('payCash').value)};}
function detailsHtml(d){
 return `<p class="muted">${esc(d.basis)}</p><div class="pay-statement-summary"><div>Commission<strong>${dollar(d.commission)}</strong></div><div>Parts reimbursement<strong>${dollar(d.reimbursement)}</strong></div><div>${d.netDue<0?'Technician owes company':'Amount due'}<strong>${dollar(Math.abs(d.netDue))}</strong></div></div><p>Pre-tax revenue ${dollar(d.revenue)} · Parts ${dollar(d.parts)} · Confirmed cash retained ${dollar(d.cashRetained)}</p><p>Customer collections: ${Object.entries(d.methods).map(([m,n])=>esc(m)+' '+dollar(n)).join(' · ')||'None'}</p><div class="pay-statement-table"><table class="list"><thead><tr><th>Date / customer / invoice</th><th>Pre-tax</th><th>Parts / payer</th><th>Commission</th><th>Reimbursement</th><th>Total</th></tr></thead><tbody>${d.rows.map(r=>`<tr><td>${esc(r.date)}<br><b>${esc(r.customer)}</b><br>${esc(r.title)}<br>${esc(r.invoices.join(', '))}</td><td>${dollar(r.revenue)}</td><td>${dollar(r.parts)}<br>${esc(r.partsPaidBy)}</td><td>${dollar(r.commission)}</td><td>${dollar(r.reimbursement)}</td><td>${dollar(r.entitlement)}</td></tr>`).join('')}</tbody></table></div>${d.excluded.length?`<details style="margin-top:12px"><summary>${d.excluded.length} jobs excluded · review reasons</summary>${d.excluded.map(j=>`<p>${esc(j.customer||j.title)} — ${esc(j.reason)}</p>`).join('')}</details>`:''}`;
}
function status(message){if(get('payStatus'))get('payStatus').textContent=message;}
function invalidate(){preview=null;if(get('paySave'))get('paySave').disabled=true;status('Inputs changed. Preview the calculation again.');}
window.TechnicianPayroll={
 choose(){if(!canOperateOffice())return;showModal({title:'Technician files',body:`<label class="field"><span class="lbl">Choose technician</span><select id="payTechChoice">${techs().map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}</select></label><button class="btn btn-primary" onclick="TechnicianPayroll.open(document.getElementById('payTechChoice').value)" ${techs().length?'':'disabled'}>Open technician file</button>`});},
 async open(id){
  if(!canOperateOffice())return;current=getOne('team',id);if(!current)return;epoch++;const token=epoch;preview=null;saved=null;history=[];payments=[];const range=lastWeek(),cfg=current.payroll_reminder||{};
  showModal({title:esc(current.name)+' · Technician file',wide:true,body:`<p class="muted">Saved statements, recorded payments and weekly reminders.</p><div class="field-row"><label class="field"><span class="lbl">From (included)</span><input type="date" id="payFrom" value="${range.from}" onchange="TechnicianPayroll.invalidate()"></label><label class="field"><span class="lbl">Until (excluded)</span><input type="date" id="payTo" value="${range.to}" onchange="TechnicianPayroll.invalidate()"></label></div><div class="field-row"><label class="field"><span class="lbl">Commission %</span><input id="payRate" type="number" min="0" max="100" step="0.1" value="${Number(current.commissionPercent)||0}" onchange="TechnicianPayroll.invalidate()"></label><label class="field"><span class="lbl">Cash retained by technician · confirmed ($)</span><input id="payCash" type="number" min="0" step="0.01" value="0" onchange="TechnicianPayroll.invalidate()"></label></div><p class="muted">Sunday to Sunday covers seven days. Only completed jobs with fully paid invoices are payable; saved statements prevent including the same job twice. Cash stays at zero unless you confirm the technician kept it.</p><div class="payroll-tools"><button class="btn btn-primary" id="payPreview" onclick="TechnicianPayroll.preview()">Preview calculation</button>${owner()?'<button class="btn" id="paySave" disabled onclick="TechnicianPayroll.save()">Generate & save pay statement</button>':''}</div><p id="payStatus" role="status" aria-live="polite"></p><div id="payDetails"></div><details class="premium-wand"><summary>${PremiumTools.icon('clock')} Weekly payment reminder</summary><p>Creates an in-app payment review notification each week in the selected time zone.</p><label><input id="payReminderEnabled" type="checkbox" ${cfg.enabled?'checked':''}> Enable weekly reminder</label><div class="field-row"><label class="field"><span class="lbl">Weekday</span><select id="payReminderDay">${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i)=>`<option value="${i}" ${Number(cfg.weekday||0)===i?'selected':''}>${d}</option>`).join('')}</select></label><label class="field"><span class="lbl">Hour</span><select id="payReminderHour">${Array.from({length:24},(_,i)=>`<option value="${i}" ${Number(cfg.hour??9)===i?'selected':''}>${String(i).padStart(2,'0')}:00</option>`).join('')}</select></label></div><label class="field"><span class="lbl">Time zone</span><select id="payReminderZone">${['America/New_York','America/Chicago','America/Denver','America/Los_Angeles'].map(z=>`<option ${cfg.time_zone===z?'selected':''}>${z}</option>`).join('')}</select></label>${owner()?'<button class="btn" id="payReminderSave" onclick="TechnicianPayroll.reminder()">Save reminder settings</button>':'<p>Ask the owner to configure payment reminders.</p>'}<p id="payReminderStatus" role="status"></p></details><h3>Saved statements · latest 50</h3><div id="payHistory" role="status">Loading…</div>`});
  try{const {data,error}=await SB.from('technician_pay_statements').select('*').eq('technician_id',id).order('created_at',{ascending:false}).limit(50);if(error)throw error;if(token!==epoch||!get('payHistory'))return;history=data||[];get('payHistory').innerHTML=history.map(s=>`<div class="pay-statement-history"><div><b>${esc(s.period_from)} → ${esc(s.period_to)}</b><br>${dollar(s.net_due)} · ${esc(s.status)}</div><button class="btn btn-sm" onclick="TechnicianPayroll.statement(${arg(s.id)})">Open statement</button></div>`).join('')||'<p>No saved statements yet.</p>';}
  catch{if(token===epoch&&get('payHistory'))get('payHistory').textContent='Could not load statements. Reopen this file to try again.';}
 },invalidate,
 async preview(){if(busy||!current)return;busy=true;const token=epoch,input=fields(),button=get('payPreview');button.disabled=true;invalidate();status('Calculating from saved jobs and payments…');try{const result=await api({action:'preview',...input});if(token!==epoch||!get('payDetails'))return;if(JSON.stringify(fields())!==JSON.stringify(input)){invalidate();return;}preview={...result,input};get('payDetails').innerHTML=detailsHtml(result.details);if(get('paySave'))get('paySave').disabled=!result.details.rows.length;status('Preview ready. Review the breakdown before generating a saved statement.');}catch(e){if(token===epoch)status(e.message);}finally{busy=false;if(button.isConnected)button.disabled=false;}},
 async save(){if(busy||!preview||!owner())return;const ready=preview;if(JSON.stringify(fields())!==JSON.stringify(ready.input)){invalidate();return;}busy=true;const token=epoch;get('paySave').disabled=true;status('Saving your pay statement…');try{const result=await api({action:'create',...ready.input,request_id:ready.requestId||(ready.requestId=crypto.randomUUID()),expected_details:ready.fingerprint});if(token!==epoch)return;history.unshift(result.statement);await this.statement(result.statement.id);}catch(e){if(token===epoch){status(e.message);if(get('paySave'))get('paySave').disabled=false;}}finally{busy=false;}},
 async statement(id){
  const s=history.find(x=>x.id===id);if(!s)return;saved=s;epoch++;const token=epoch;
  const {data,error}=await SB.from('technician_pay_statement_payments').select('*').eq('statement_id',id).order('created_at');if(token!==epoch)return;if(error)return toast('Could not load payment history.',true);payments=data||[];
  const paid=payments.reduce((sum,p)=>sum+Number(p.amount),0),remaining=Math.round((Number(s.net_due)-paid)*100)/100;
  showModal({title:esc(s.details.technician)+' · Pay statement',wide:true,body:`<p><b>${esc(s.period_from)} → ${esc(s.period_to)}</b> · End date excluded · ${esc(s.status)}<br><span class="muted">Statement ${esc(s.id)} · Generated ${esc(s.created_at.slice(0,10))}</span></p>${detailsHtml(s.details)}<div class="pay-statement-summary"><div>Recorded payments<strong>${dollar(paid)}</strong></div><div>${remaining<0?'Owed to company':'Remaining to pay'}<strong>${dollar(Math.abs(remaining))}</strong></div></div><div class="payroll-tools"><button class="btn btn-primary" onclick="TechnicianPayroll.pdf()">Download pay statement PDF</button><button class="btn" onclick="TechnicianPayroll.share()">Share statement</button>${owner()&&s.status!=='void'&&remaining>0?'<button class="btn" onclick="TechnicianPayroll.paymentForm()">Pay technician / record transfer</button>':''}${owner()&&s.status!=='void'&&!payments.length?'<button class="btn btn-danger" onclick="TechnicianPayroll.voidForm()">Void unpaid statement</button>':''}</div><h4>Payment history</h4>${payments.map(p=>`<p>${esc(p.paid_on)} · ${esc(p.method)} · ${dollar(p.amount)} · ${esc(p.reference)}</p>`).join('')||'<p>No payments recorded.</p>'}<div id="payRecordForm"></div><p id="payStatus" role="status"></p>`});
 },
 paymentForm(){if(!owner()||!saved||saved.status==='void')return;const remaining=Number(saved.net_due)-payments.reduce((s,p)=>s+Number(p.amount),0);get('payRecordForm').innerHTML=`<section class="premium-wand"><h4>Pay technician</h4><p>Complete the transfer in your bank or Zelle, then record the actual payment here.</p><a class="btn" href="https://www.bankofamerica.com/" target="_blank" rel="noopener noreferrer">Open Bank of America</a><div class="field-row"><label class="field"><span class="lbl">Actual amount paid ($)</span><input type="number" id="payActualAmount" min="0.01" max="${remaining}" step="0.01" value="${remaining.toFixed(2)}"></label><label class="field"><span class="lbl">Paid date</span><input type="date" id="payActualDate" max="${todayISO()}" value="${todayISO()}"></label></div><label class="field"><span class="lbl">Method</span><select id="payActualMethod"><option>Bank transfer</option><option>Zelle</option><option>Cash</option><option>Check</option></select></label><label class="field"><span class="lbl">Transfer reference / cash acknowledgement</span><input id="payActualReference" maxlength="250"></label><label><input id="payActualConfirmed" type="checkbox"> I confirm this payment was completed.</label><div class="payroll-tools"><button id="payActualSave" class="btn btn-primary" onclick="TechnicianPayroll.record()">Record completed payment</button></div></section>`;this.paymentRequest=crypto.randomUUID();},
 async record(){if(busy||!owner()||!saved)return;if(!get('payActualConfirmed')?.checked||!get('payActualReference')?.value.trim())return toast('Confirm the completed payment and enter a reference.',true);busy=true;const id=saved.id,token=epoch,button=get('payActualSave');button.disabled=true;try{const {error}=await SB.rpc('record_technician_pay_payment',{p_id:this.paymentRequest,p_statement:id,p_amount:Number(get('payActualAmount').value),p_method:get('payActualMethod').value,p_reference:get('payActualReference').value.trim(),p_paid_on:get('payActualDate').value});if(error)throw error;const {data,error:se}=await SB.from('technician_pay_statements').select('*').eq('id',id).single();if(se)throw se;if(token!==epoch)return;history=history.map(s=>s.id===id?data:s);await this.statement(id);toast('Actual technician payment recorded.');}catch(e){if(token===epoch)status(e.message||'Could not record payment.');}finally{busy=false;if(button.isConnected)button.disabled=false;}},
 voidForm(){get('payRecordForm').innerHTML='<section class="premium-wand"><p>Void this unpaid statement and release its jobs for recalculation. The original statement remains in history.</p><button class="btn btn-danger" onclick="TechnicianPayroll.void()">Confirm void unpaid statement</button></section>';},
 async void(){if(busy||!owner()||!saved)return;busy=true;const id=saved.id,techId=saved.technician_id;try{const {error}=await SB.rpc('void_technician_pay_statement',{p_statement:id});if(error)throw error;await this.open(techId);toast('Unpaid statement voided.');}catch(e){status(e.message);}finally{busy=false;}},
 async reminder(){if(!owner()||!current)return;const token=epoch,button=get('payReminderSave');button.disabled=true;try{const cfg={enabled:get('payReminderEnabled').checked,weekday:Number(get('payReminderDay').value),hour:Number(get('payReminderHour').value),time_zone:get('payReminderZone').value};const {error}=await SB.rpc('set_technician_pay_reminder',{p_technician:current.id,p_settings:cfg});if(error)throw error;current.payroll_reminder=cfg;if(token===epoch&&get('payReminderStatus'))get('payReminderStatus').textContent=cfg.enabled?'Weekly payment review reminder enabled.':'Weekly reminder disabled.';}catch(e){if(token===epoch&&get('payReminderStatus'))get('payReminderStatus').textContent=e.message;}finally{if(button.isConnected)button.disabled=false;}},
 makePdf(){
  if(!saved)throw new Error('Open a saved statement first.');const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'pt',format:'letter'}),d=saved.details;let y=50;
  function line(text,bold=false){pdf.setFont('helvetica',bold?'bold':'normal');pdf.setFontSize(bold?12:10);for(const part of pdf.splitTextToSize(String(text),510)){if(y>735){pdf.addPage();y=50;}pdf.text(part,50,y);y+=15;}}
  pdf.setTextColor(8,40,83);line('EZfix Garage Doors Inc · Technician Pay Statement',true);line(d.technician,true);line('Period: '+d.from+' through '+d.to+' (end excluded)');line('Statement: '+saved.id);line('Generated: '+saved.created_at.slice(0,10)+' · Status: '+saved.status);line('Commission rate: '+d.rate+'%');line(d.basis);y+=10;
  for(const r of d.rows){line(r.date+' · '+r.customer+' · '+r.title,true);line('Invoices: '+r.invoices.join(', '));line('Pre-tax revenue '+dollar(r.revenue)+' · Parts '+dollar(r.parts)+' ('+r.partsPaidBy+')');line('Profit '+dollar(r.profit)+' · Commission '+dollar(r.commission)+' · Reimbursement '+dollar(r.reimbursement));line('Collections: '+r.collections.map(p=>p.method+' '+dollar(p.amount)).join(', '));line('Technician entitlement: '+dollar(r.entitlement));y+=8;}
  line('Totals',true);line('Pre-tax revenue: '+dollar(d.revenue)+' · Parts: '+dollar(d.parts));line('Commission: '+dollar(d.commission)+' · Parts reimbursement: '+dollar(d.reimbursement));line('Entitlement: '+dollar(d.entitlement)+' · Confirmed retained cash: '+dollar(d.cashRetained));line('Net due: '+dollar(d.netDue),true);const paid=payments.reduce((s,p)=>s+Number(p.amount),0);line('Recorded payments: '+dollar(paid)+' · Remaining: '+dollar(Number(saved.net_due)-paid),true);for(const p of payments)line(p.paid_on+' · '+p.method+' · '+dollar(p.amount)+' · '+p.reference);y+=10;line('Business commission settlement statement. Tax withholding and statutory payroll deductions are not calculated.');return pdf;
 },pdf(){try{this.makePdf().save('EZfix-pay-statement-'+saved.period_from+'-'+saved.period_to+'.pdf');}catch(e){toast(e.message,true);}},
 async share(){try{const file=new File([this.makePdf().output('blob')],'EZfix-pay-statement-'+saved.period_from+'.pdf',{type:'application/pdf'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'EZfix technician pay statement'});else this.pdf();}catch(e){if(e.name!=='AbortError')toast('Could not share statement. Download the PDF instead.',true);}}
};
})();
