import { createClient } from "npm:@supabase/supabase-js@2";
const url=Deno.env.get("SUPABASE_URL")!, service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-ezfix-form-token","Access-Control-Allow-Methods":"POST,OPTIONS"};
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"content-type":"application/json"}});
const normalize=(p:string)=>{const d=String(p||"").replace(/\D/g,"");if(d.length===10)return "+1"+d;if(d.length===11&&d.startsWith("1"))return "+"+d;return String(p||"").startsWith("+")?"+"+d:"";};
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS") return new Response("ok",{headers:cors});
 if(req.method!=="POST") return out({error:"method_not_allowed"},405);
 const expected=Deno.env.get("WEBSITE_SMS_CONSENT_TOKEN")||"";
 const supplied=req.headers.get("x-ezfix-form-token")||"";
 if(!expected) return out({error:"website_consent_not_configured"},503);
 if(supplied!==expected) return out({error:"unauthorized"},401);
 const body=await req.json().catch(()=>null);
 const phone=normalize(body?.phone||"");
 const consented=body?.sms_consent===true;
 const submissionId=String(body?.submission_id||"").trim();
 const consentText=String(body?.consent_text||"").trim();
 const consentVersion=String(body?.consent_version||"").trim();
 const sourceUrl=String(body?.source_url||"").trim();
 if(!/^\+[1-9]\d{7,14}$/.test(phone)) return out({error:"invalid_phone"},400);
 if(!consented) return out({error:"explicit_sms_consent_required"},400);
 if(!submissionId||!consentText||!consentVersion) return out({error:"consent_evidence_required"},400);
 const now=new Date().toISOString();
 const row={phone_e164:phone,status:"opted_in",source:"website_form",last_keyword:null,opted_in_at:now,opted_out_at:null,consent_text:consentText,consent_version:consentVersion,source_url:sourceUrl||null,form_submission_id:submissionId,updated_at:now};
 const {error}=await admin.from("sms_consent").upsert(row,{onConflict:"phone_e164"});
 if(error) return out({error:"consent_persist_failed"},500);
 return out({success:true,status:"opted_in",phone});
});