import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

// Keep Vercel's buildCommand short while retaining every existing release gate.
// Run sequentially: failed tests stop the build, and transforms keep their order.
const scripts = [
  'test-notification-alerts.mjs',
  'build-notification-alerts.mjs',
  'test-public-routes.mjs',
  'audit-public-routes.mjs',
  'audit-invoice-preview-access.mjs',
  'audit-public-invoice-totals.mjs',
  'audit-public-invoice-token.mjs',
  'audit-website-sms-consent.mjs',
  'audit-website-intake.mjs',
  'audit-website-lead-review.mjs',
  'audit-invoice-email-link.mjs',
  'square-live-integration-audit.mjs',
  'audit-ui-state.mjs',
  'build-ui-state.mjs',
  'audit-product-catalog-ui.mjs',
  'audit-catalog-labor-metadata.mjs',
  'audit-quickpay-recovery.mjs',
  'audit-dispatch-sms-receipts.mjs',
  'audit-ashley-dispatch.mjs',
  'test-ashley-demo-matrix.mjs',
  'run-grand-dispatch-demo.mjs',
  'test-dispatch-demo.mjs',
  'audit-ashley-complex-routing.mjs',
  'audit-ashley-setup.mjs',
  'audit-job-assignment.mjs',
  'job-completion-signature-audit.mjs',
  'audit-job-completion-refresh.mjs',
  'audit-office-role.mjs',
  'audit-whatsapp-linked-device.mjs',
  'audit-invoice-contact.mjs',
  'audit-payroll-integrity.mjs',
  'audit-report-history.mjs',
  'audit-technician-earnings.mjs',
  'audit-activity-history.mjs',
  'audit-lead-offer-channels.mjs',
  'audit-lead-offer-ui.mjs',
  'audit-lead-approval.mjs',
  'audit-dispatch-review.mjs',
  'audit-modal-actions.mjs',
  'audit-navigation-groups.mjs',
  'audit-workspace-pages.mjs',
  'build-product-catalog-ui.mjs',
  'audit-visualizer-gallery-premium.mjs',
  'build-visualizer-gallery-premium.mjs',
  'audit-marketing-connections-ui.mjs',
  'build-marketing-connections-ui.mjs',
  'audit-assignment-whatsapp.mjs',
  'build-assignment-whatsapp.mjs',
  'audit-call-recordings.mjs',
  'audit-provider-recording-persistence.mjs',
  'audit-recording-download.mjs',
  'audit-transcript-replay.mjs',
  'audit-transcript-replay-integration.mjs',
  'audit-call-audio-access.mjs',
  'audit-replay-storage-preflight.mjs',
  'build-transcript-replay-ui.mjs',
  'audit-calendar-overlap.mjs',
  'audit-calendar-date-display.mjs',
  'audit-calendar-appointment-times.mjs',
  'build-calendar-overlap.mjs',
  'audit-calendar-premium.mjs',
  'build-calendar-premium.mjs',
  'audit-ui-state.mjs',
  'audit-product-catalog-ui.mjs',
  'audit-visualizer-gallery-premium.mjs',
  'audit-marketing-connections-ui.mjs',
  'audit-assignment-whatsapp.mjs',
  'audit-call-recordings.mjs',
  'audit-transcript-replay-integration.mjs',
  'audit-superezx-telephony-adapter.mjs',
  'build-door-design-library.mjs',
  'audit-door-design-library.mjs',
  'audit-door-config-options.mjs',
  'build-door-gallery.mjs',
  'audit-door-gallery.mjs'
];
const root = fileURLToPath(new URL('../', import.meta.url));
for (const script of scripts) {
  console.log(`\nRelease step: ${script}`);
  execFileSync(process.execPath, [fileURLToPath(new URL(script, import.meta.url))], {
    cwd: root,
    stdio: 'inherit'
  });
}
console.log('\nAll release steps completed.');
