-- Atomic anonymous website-lead rate limiting.
create table if not exists public.website_lead_rate_events (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.website_lead_rate_events enable row level security;
revoke all on table public.website_lead_rate_events from public, anon, authenticated;
grant select, insert, delete on table public.website_lead_rate_events to service_role;

create index if not exists website_lead_rate_events_key_created_idx
  on public.website_lead_rate_events(key_hash, created_at desc);

create or replace function public.service_check_website_lead_rate_limit(
  p_key_hash text,
  p_limit integer default 8,
  p_window_seconds integer default 900
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_now timestamptz := now();
  v_since timestamptz;
  v_count integer;
  v_oldest timestamptz;
  v_retry integer := 0;
begin
  if nullif(btrim(coalesce(p_key_hash,'')),'') is null then
    raise exception 'rate limit key required';
  end if;
  if p_limit < 1 or p_limit > 100 or p_window_seconds < 60 or p_window_seconds > 86400 then
    raise exception 'invalid rate limit settings';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_key_hash));
  v_since := v_now - make_interval(secs => p_window_seconds);

  delete from public.website_lead_rate_events
  where created_at < v_now - interval '24 hours';

  select count(*), min(created_at)
    into v_count, v_oldest
  from public.website_lead_rate_events
  where key_hash = p_key_hash
    and created_at >= v_since;

  if v_count >= p_limit then
    v_retry := greatest(1, ceil(extract(epoch from ((v_oldest + make_interval(secs => p_window_seconds)) - v_now)))::integer);
    return jsonb_build_object('allowed',false,'count',v_count,'limit',p_limit,'retry_after',v_retry);
  end if;

  insert into public.website_lead_rate_events(key_hash) values (p_key_hash);
  return jsonb_build_object('allowed',true,'count',v_count+1,'limit',p_limit,'retry_after',0);
end;
$function$;

revoke all on function public.service_check_website_lead_rate_limit(text,integer,integer)
from public, anon, authenticated;
grant execute on function public.service_check_website_lead_rate_limit(text,integer,integer)
to service_role;
